### ISSUE TITLE
Limiting packet size after first

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#505] opened 2017-05-05 01:26 UTC
This is mostly editorial work, but there's an addition that I recommend. To avoid packets getting dropped in the network later in a connection, all packets in a connection MUST be no larger than the first packet in the connection.

**Comment by ekr** [comment] 2017-05-05 01:30
Maybe I'm confused, but doesn't this basically preclude any kind of PMTU discovery. My reasoning is:

1. The first packet MUST be safe to send, so ~1280 bytes.
2. If I can't send any packet later, then I can't probe for higher MTUs.

**Comment by martinthomson** [comment] 2017-05-05 01:40
Yep, this would seem to contradict what we've already decided.  Also, it's hardly editorial.

**Comment by janaiyengar** [comment] 2017-05-05 02:18
@ekr: Right, sorry, I misspoke. The point was to say that a client should use higher packet sizes only if it's actively doing PMTUD. I wasn't clear in my description.

@martinthomson My intent was different than the words that came out; I don't believe what I just clarified contradicts what we have. I've added a design label and happy to split this issue out into a separate one from the refactor.

**Comment by martinthomson** [comment] 2017-05-05 02:22
Ahh, I see.  There's a risk that you prohibit PMTUD by making this a MUST, but that's avoidable with the right conditionals.

If you think of the first packet as the first attempt at PMTUD, then this might just be unnecessary.  You detect the PMTU as you are able and send packets within it as you see fit.

**Comment by janaiyengar** [comment] 2017-05-05 02:49
Yeah, the point was to ensure that an impl that doesn't do mid-connection PMTUD doesn't use an MTU larger than what was used for the first packet. Avoids surprises.

**Comment by martinthomson** [comment] 2017-05-08 00:41
I notice now that we're discussing what @janaiyengar intended to be a small addition and the original reason for opening this issue was a pure duplicate of #463.

**Comment by ianswett** [comment] 2018-03-13 16:10
No longer an issue, see section 9.4 Path Maximum Transmission Unit.

**Closed by ianswett** 2018-03-13 16:10 UTC
Labels: -transport, design

**Comment by mikkelfj** [comment] 2018-03-13 16:36
It's section 8.4 not 9.4 - it says some implementations may choose a more conserative size due to possible tunneling overhead. But that isn't possible when the handshake is forced to the maximum - should there be an issue to limit handshake size to, say, 1000 bytes?
