### ISSUE TITLE
Why are error codes not a varint?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1940] opened 2018-10-31 03:48 UTC
The error codes in CONNECTION_CLOSE and RST_STREAM frames are uint16s. That's inconsistent with how we encode pretty much every other value.

While saving bytes is not the reason I'm opening this issue, depending on how frequently streams are reset, it might be nice to save a byte on the error code as well.

**Comment by kazuho** [comment] 2018-10-31 07:52
I think there are pros and cons in using a varint.

The pro is that we'd have a chance to save an octet as have been pointed out.

The cons that I see are:
* It would not give us any benefit when the application protocol defines error codes in groups (e.g., upper 8 bits indicate the category of the error and lower 8 bits indicate the details). To generalize, I am not sure if we can anticipate that the number space will be used from 0 and onwards unlike other variables that we send.
* It is a bit strange to state that an error code is a *62*-bit variable rather than a type that uses a multiple of 8-bits.

I do not have a strong opinion but considering the cons sticking with `uint16_t` is not too strange to me.

**Comment by ianswett** [comment] 2018-10-31 11:07
I tend to agree with you, and as a related point, I never understood why we moved off 32 bit error codes, but I also don't think it ends up mattering much so I'm not itching to change it at this point.

If others want to, that's fine with me, since updating from uint16 to varint is easy, but it does seem a bit late for this change in v1.

**Comment by martinthomson** [comment] 2018-11-01 01:06
When I did the varint transition, I chose a fixed size for error codes because they don't represent something that increases, but are more an enumeration.  With the change to varint frame types, that argument doesn't hold any more.  I'm not complete opposed to the idea of varint here, but I would request that a PR be presented before we meet.

@marten-seemann, you have time on the agenda for talking about varint transport parameters.  I won't object if you asked about this at the same time.  Though anyone might reasonably object to a change, I don't think it's fair to deny the discussion.  Particularly if it can be kept short.

**Comment by dtikhonov** [comment] 2018-11-01 13:17
Varint transport parameters are not on the agenda here:

https://github.com/quicwg/wg-materials/blob/76f20bb7095c3b7f6565c39fd4f429d6311ae9f7/ietf103/agenda.md

**Comment by martinthomson** [comment] 2018-12-13 05:40
I'm going to suggest that the statute of limitations has expired on this one.  Does anyone want to drive this, or should I close it?

**Comment by kazuho** [comment] 2018-12-13 06:01
My not-so-strong preference goes to closing the issue. It's not a bug to use uint16_t, this issues should not block -17, once -17 ships we should only make changes that are essential for the protocol to work correctly.

**Comment by martinthomson** [comment] 2018-12-13 06:05
Right.  That's my thinking also.  Though I don't think that -17 will be as firm as you might have liked, unless we decide to reject some of the proposals we have in flight.  I personally want to reject a lot of those, but we'll see how that goes.  Current plan is to ship 24 hours.  I'll hold this open until then.

**Comment by mikkelfj** [comment] 2018-12-13 09:07
Are there any big endian integer encoding besides error codes and TP? I think the compelling case would be if QUIC has NO big endian encoding at all. Otherwise it is a matter of taste.

**Comment by mikkelfj** [comment] 2018-12-13 09:39
I'm not arguing against big endian per se (well I would, in a separate discussion), but the endianness is a moot point if all encodings are opaque or varint - and it would be nice to sidestep that discussion if there are only a few hold-outs left.

**Comment by martinthomson** [comment] 2018-12-13 23:22
Versions are fixed size also.  Packet numbers are similarly special.

Thanks all.

**Closed by martinthomson** 2018-12-13 23:22 UTC
Labels: -transport, design
