### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#159] opened 2017-01-16 10:45 UTC
There already is a "`DISCUSS_AND_REPLACE: Perhaps make this format simpler`" note in the spec about the homegrown floating point format used for ACK timestamps. I just wanted to open a corresponding issue.

It would be really good if an encoding could be used that was either trivial to implement from scratch, or a standard for which code is readily available.

As for the latter, the text in the spec sounds like what is desired is something like the ["binary16" format in IEEE 754-2008](https://en.wikipedia.org/wiki/Half-precision_floating-point_format). I'd be great if this could be used. Compiler support seems spotty/sketchy, e.g., [gcc says this](https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html):

> The __fp16 type may only be used as an argument to intrinsics defined in <arm_fp16.h>, or as a storage format. For purposes of arithmetic and other operations, __fp16 values in C or C++ expressions are automatically promoted to float. 

And it's only supported on ARM, apparently.

**Comment by ghedo** [comment] 2017-01-16 12:45
Isn't this a duplicate of #109?

**Comment by larseggert** [comment] 2017-01-16 13:55
Probably, although it's a bit terse. (I tried to look if someone had raised this, but didn't find #109.)

**Comment by ianswett** [comment] 2017-01-16 14:23
In #109, which is in the needs discussion list, I propose we switch to scaled uint16s.

**Comment by mnot** [comment] 2017-01-20 02:42
Copied comment over there; closing this as dup.

**Closed by mnot** 2017-01-20 02:42 UTC
Labels: design, transport
