### ISSUE TITLE
Allow PMTU probing of a path suspected of not supporting PMTU of 1280

### ISSUE THREAD

**Issue by igorlord** [quicwg/base-drafts#2118] opened 2018-12-12 00:48 UTC
The current "Path Maximum Transmission Unit (PMTU)" text requires endpoints to "immediately cease sending QUIC packets" on a path that PMTU discovery mechanism suggested has fallen below 1280.

This may be a damaging recommendation, especially if no alternative path is available.  PMTU discovery is not perfect and network conditions are not permanent -- it is more likely that a temporary network condition caused too many PMTU probe losses than a durable routing change causing packets to flow over a very narrow pipe.

Hence, PR #2108 suggests that endpoints may continue probing the path.

**Comment by martinthomson** [comment] 2019-01-30 06:55
PR #2108 was merged and @igorlord agrees that the issue is fixed.

**Closed by martinthomson** 2019-01-30 06:55 UTC
Labels: -transport, design
