### ISSUE TITLE
AEAD Associated Data

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#243] opened 2017-01-26 20:52 UTC
The TLS draft currently states that the associated data for AEAD encryption is the empty sequence. This is a deviation from legacy QUIC, which uses the public header as associated data and thus authenticates those fields. Packet number authentication is already accomplished due to its inclusion in the IV.

In Tokyo, there was considerable interest in a couple of features that require integrity of Public Header fields:
- Greasing the unused bits in the Public flags
- The connection ID may be used for routing.

It is probable that firewalls might block unused public flag bits, particularly if any middlebox could potentially alter them without detection to send a signal.

Therefore, I suggest that we restore use of the full publice header as associated data. I see no reason that this would impose excessive costs on the receiver.

I believe @janaiyengar brought this issue up first, though I fully endorse it.

**Comment by ianswett** [comment] 2017-01-26 22:20
I would agree with this proposal, for all the reasons you mentioned.  This becomes critical if anything new is added in the unencrypted portion of the packet.

**Comment by martinthomson** [comment] 2017-02-02 01:12
We discussed this at the interim and the sense (myself excluded), was that adding the header to the AAD was desirable.  That's a relatively small change and I can take that on.

**Comment by martinthomson** [comment] 2017-02-02 01:13
OK, now this is actually a duplicate of #226.  I'll take that instead.

**Closed by martinthomson** 2017-02-02 01:13 UTC
Labels: design, notify-consensus, tls, transport
