### ISSUE TITLE
Does PMTU fail really want unauthenticated PUBLIC_RESET?

### ISSUE THREAD

**Issue by mcmanus** [quicwg/base-drafts#327] opened 2017-02-20 04:01 UTC
section 8 of transport:`

>  If a QUIC endpoint determines that the PMTU between any pair of local and remote IP addresses has fallen below 1280 octets, it MUST immediately cease sending QUIC packets between those IP addresses. This may result in abrupt termination of the connection if all pairs are affected. In this case, an endpoint SHOULD send a Public Reset packet to indicate the failure. 

but PR is defined as being a last resort and it is of course not authenticated.. while it is short, a CONNECTION_CLOSE only packet would also be below minimum MTUs for IPvmumble, and is authenticated and could carry some diagnostic information.

It seems like this error can be authenticated and therefore should be.. and more generally we shouldn't promote error reporting to RST as its interaction with already sent data is very unclear if TCP RST is any kind of corollary.
`

**Comment by RyanAtGoogle** [comment] 2017-02-20 23:14
Totally agree. CONNECTION_CLOSE seems much more appropriate here.

**Comment by martinthomson** [comment] 2017-02-20 23:34
Duplicate of #289.

(FWIW, my reading of the list is that this is unequivocally good.)

**Closed by martinthomson** 2017-02-20 23:34 UTC
