### ISSUE TITLE
Handling un-ackable packets

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#751] opened 2017-08-28 21:59 UTC
Consider the case f the client is attempting 0-RTT and sends the sequence:

 CI (1), Data(2), Data(3)  // packet numbers in parens

Now, what happens if CI(1) is lost? The server cannot ACK packets 2, 3 because (a) it's forbidden and (b) it can't validate their integrity. So, it seems like what happens is just that eventually the client times out and retransmits CI, which means that the performance here is limited by the client's RTO, as opposed to if (say) the server's first flight was lost, when the QUIC ACKs can force faster retransmission. 

What I've been considering for DTLS is to have the receiver send an empty ACK (i.e,, one that acknowledges no packets), but that's not possible because of the QUIC ACK structure which requires you to ACK at least one packet.

**Comment by martinthomson** [comment] 2017-08-29 00:31
Yes, this isn't a great outcome.  The server can trigger fast retransmission of the CI by sending a stateless retry, but that means discarding 0-RTT data.

There is a more aggressive timer on the retransmission of CI, which helps a little.  There is also text that suggests that holding 0-RTT is potentially useful (though risky).  Do you think that we need a fast retransmission trigger?

**Comment by ekr** [comment] 2017-08-29 00:42
Well, it's relatively fine to hold this 0-RTT data b/c you can't decrypt it anyway (modulo potential DoS issues).

The solution I would propose here is that when we update the ACK frame, we allow an empty ACK, and then that can be used for fast retransmission

**Comment by RyanAtGoogle** [comment] 2017-08-30 23:37
On Mon, Aug 28, 2017 at 5:42 PM, ekr <notifications@github.com> wrote:

> Well, it's relatively fine to hold this 0-RTT data b/c you can't decrypt
> it anyway (modulo potential DoS issues).
>
> The solution I would propose here is that when we update the ACK frame, we
> allow an empty ACK, and then that can be used for fast retransmission
>
​This seems reasonable to me. It would every so slightly complicate the
implementation of a "stateless" server (which delays the creation of the
connection until a valid client hello arrives), because presumably these
"empty" ACK frames would be delivered in packets which would consume packet
number space. So when the server finally gets around to responding the the
client's handshake, it would need to account for the packet numbers
consumed by those packets. I don't think this is a problem, just a detail.

​Cheers,

Ryan​

**Comment by martinthomson** [comment] 2017-08-31 00:12
@RyanAtGoogle, Maybe we can deal with the packet number issue by minting another packet type.  That might be best given that we would have nothing to send in this packet and ideally you want to ensure that you have a way for the server to show that it actually received a packet (triggering retransmission isn't that big of a deal, but if we can prevent off-path entities from doing that cheaply, that's worth doing).

**Comment by RyanAtGoogle** [comment] 2017-08-31 01:26
Sure, that sounds plausible too. Perhaps add a hash of the received packet contents into the body of this new packet type?

**Comment by martinthomson** [comment] 2017-08-31 01:32
See #693.  I think that we would take the conclusion of that.  (Right now that's agreed, I think, but waiting on some restructuring of the document, which in turn is waiting for our PR backlog to thin out some more.)

**Comment by RyanAtGoogle** [comment] 2017-08-31 18:37
The idea being that echoing back the connection ID (plus the version specific AEAD) would be sufficient proof of receipt? SGTM

**Comment by MikeBishop** [comment] 2017-09-06 23:08
The new packet type idea seems like a valid approach -- we already have packets (ab)using the packet number field to echo the received packet number statelessly rather than consuming a packet number on the server side.  (See VN, Stateless Retry.)  Defining an "Unprocessed Data" packet that does the same thing and has no payload would follow the pattern, at least.

**Comment by martinthomson** [comment] 2018-01-16 01:40
Right now we don't have any way to signal this with an ACK frame (the encoding demands a minimum acknowledgment set of size 1).  We could amend that frame type, but that affects far more than this one usage.  Given the unique circumstances an empty packet of a new type seems awful, but not that much more than the alternatives.  We could also just use Handshake with no content, but that sort of overloading might be unwise.

**Comment by mikkelfj** [comment] 2018-01-16 09:14
How about CONNECTION_CLOSE 0RTT_LOST. A 0-RTT retransmission could make use of buffered packets at receiver by noting the 0-RTT handshake is a retransmission, if that is worthwhile?

**Comment by martinthomson** [comment] 2018-01-16 23:29
CONNECTION_CLOSE isn't appropriate here.  It implies dropping state, where the server might save the 0-RTT until it gets the missing handshake message.

**Comment by janaiyengar** [comment] 2018-01-17 02:35
Since this information is advisory, I would argue that the receiver should be allowed the freedom to drop this data that's being buffered, waiting for the Initial packet. Given that, it makes sense to not use the ACK frame since we would have to overload the reliability semantics of an ACK frame. I agree that a new packet type seems like the best of the available options here.

**Comment by ianswett** [comment] 2018-03-14 11:40
Parking until we have evidence to suggest it's valuable, from DTLS or elsewhere.

**Comment by ianswett** [comment] 2018-09-17 20:17
The Stream0 design team brought this up again in Kista and concluded an empty ACK frame or an equivalent was a viable approach, but the working group wasn't interested in the extra complexity.

**Comment by ianswett** [comment] 2018-10-30 22:19
I think this is a dupe of #1414 ?

**Closed by ianswett** 2018-10-30 22:19 UTC
Labels: -transport, design, parked
