### ISSUE TITLE
Still not sure what a packet or a frame is

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4289] opened 2020-10-28 14:10 UTC
>12.4.  Frames and Frame Types
>
>  The payload of QUIC packets, after removing packet protection,
  Packet Payload {
    Frame (8..) ...,
  }
>
>  consists of a sequence of complete frames, as shown in Figure 11.
  Version Negotiation, Stateless Reset, and Retry packets do not
  contain frames.

At this point (page 82) I am still not sure what a packet or a frame is and
have no idea what is going on on the wire.

**Comment by MikeBishop** [comment] 2020-10-28 20:00
Probably a duplicate of #4266.  These terms should be added to the definitions.

**Closed** 2020-11-03 23:14 UTC
Labels: -transport, ietf-lc
