### ISSUE TITLE
Single stream for headers and body

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/base-drafts#245] opened 2017-01-30 00:00 UTC
In Tokyo, we agreed that headers streams would no longer be exempt from connection-level flow control.  But the reason that headers and data streams are separate is so that one can be exempt and the other not.  So.... why are we keeping them separate again?

It might be simpler, particularly with the specter of #175 around, to bring back DATA frames and say everything's on one stream.

**Comment by martinthomson** [comment] 2017-01-30 00:48
The primary reason I have for maintaining separation is #176.  At least with separate streams, you can cancel a request without having to also cancel headers.

**Comment by marten-seemann** [comment] 2017-01-30 01:28
If I remember correctly, during this discussion we discovered that having multiple HTTP parsers operating at the same time requires a huge memory commitment on the receiving side (issue #238). Furthermore, having a smaller number of HTTP parses running than there are concurrent requests potentially leads to a deadlock caused by connection-level flow control.

The problem with HTTP/2 DATA frames is that it requires a layer violation: Since the remaining size of the packet is not known to the H2 layer, it can't create the DATA frame. This would have to be done by the QUIC layer, which ideally should be completely independent from the protocol that it is used by.

**Comment by martinthomson** [comment] 2017-01-30 01:38
That deadlock exists as long as you have the ability to fill the connection window with non-header data, so it's more a problem that is created by having headers governed by flow control.

**Comment by ianswett** [comment] 2017-01-30 02:04
Re: 2 streams per HTTP stream, I agree with Martin that the reason is you can't cancel headers streams.

**Comment by MikeBishop** [comment] 2017-01-30 02:20
@marten-seemann -- no layer violation.  DATA frames are an HTTP/2 concept, and would be on the same stream with everything else.

I should clarify my original statement of the issue -- could it be more sensible to fix this in HPACK instead of having two streams just so one of them is a cancel target?

**Comment by martinthomson** [comment] 2017-01-30 03:26
I think that @marten-seemann's point is that you have to drive frame-size decisions based on packetization.  You don't want to split a DATA frame across packets, but you don't know where a DATA frame will end up until packets are being constructed.  The HTTP layer can no longer just flush data into a buffer and leave it at that.

**Comment by MikeBishop** [comment] 2017-01-30 03:38
Perhaps I'm being stupid because I'm stuck in an airport, but... why not?  There's no requirement that the edges of the data frames line up with the packetization.  When the HTTP layer reads it, it's a bytestream.  That byte-stream contains frames -- or call them regions, if you prefer.  Those frame boundaries are independent of STREAM frame or packet boundaries.

The ugly situations I can envision are that an implementation *could* shoot itself in the foot with trailers:  QPACK encode the headers, dump a giant file into the transport, QPACK encode the trailers.  If they're all on-stream, anything that depends on the trailers (potentially other requests) will be blocked behind the giant body.  You still don't deadlock, though, because nothing stops that stream from making progress.  But you can generate some very nasty head-of-line blocking.

**Comment by martinthomson** [comment] 2017-01-30 05:07
Ahh, you are right, as long as the implementation is willing to deliver partial DATA frames, there isn't a performance penalty.

**Comment by MikeBishop** [comment] 2017-01-30 06:23
(Note that the nasty trailer situation is equally possible on two streams if the receiving implementation doesn't read the trailers until the body has arrived....)

If we went that way, I  would expect the DATA frames to be large -- either the size of the content, or the size of the chunks being handed off to the HTTP stack by the next layer.  However, there are comments on the list that being able to have framing "get out of the way" once you've hit body is attractive.

**Comment by mcmanus** [comment] 2017-01-30 13:53
I'm sympathetic to having framing get out of your way, and the 2 streams interact intuitively with cancel. So in general the split is something I support. 

maybe worth noting the link frame stuff from the unidirectional #175 concept is worth reading when thinking about where this might end up.

**Comment by krasic** [comment] 2017-06-26 22:05
Friendly bump.  

One of the problems with single stream was keeping HPACK state synchronized in the face of stream resets.   The latest QPACK solves it neatly by putting all HPACK updates on a static stream, and reference-only headers on the HTTP stream.   I think this can work for (nearly-)legacy HPACK and QCRAM too.

On the other hand, with the two stream per HTTP exchange regime, we've not heard a good simple solution to support the case of interleaving response data with PUSH_PROMISEs.  The PUSH_PROMISE ordering requirement is just a SHOULD, but it seems pretty lame to not do better.

It would be good to get this resolved as soon as possible (Prague?) because it has significant implementation implications.  My vote would be to switch back to single stream, with the tweak'd HPACK that puts updates on the static stream.

**Comment by ianswett** [comment] 2017-06-26 22:24
I would support moving towards a single stream, given all the recent pros and cons of 1 vs 2 stream models I've heard.

The request-response paradigm is nice, and if the only cost is some framing, I think it's worth it.  My only real concern about the 1 stream model before was the ability to reset a stream, but if that's been solved(or will be), 1 stream seems better.

The fact it works better for push is a perk, as well as an indication it may be a better architectural approach in general.

**Closed** 2017-07-26 18:14 UTC
Labels: -http, design
