### ISSUE TITLE
QPACK-18: Appendix B and Decoder confirming inserts

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#4245] opened 2020-10-19 13:57 UTC
Looking at Appendix B I wonder why isn't the decoder sending "Insert Count Increment" in B.4. Even if Stream 8 is cancelled, shouldn't the decoder actually acknowledge the received Encoder Stream message to do an duplicate by sending a "Insert Count Increment". I think the lack of such a message must at least be commented on?

**Comment by afrind** [comment] 2020-10-19 21:10
The example as written is not *incorrect*, since the decoder has the option to batch Insert Count Increments.  And further, there's no indication in the example that the Duplicate arrived at the decoder either.  But I agree that if that's the intent of the example, then there should be a comment to that effect...does anyone feel like one or the other is more illustrative?

**Comment by LPardue** [comment] 2020-10-19 21:14
I think, in the interest if simplicity, don't overload example if you can avoid it. Batching seems like overloading to me.

If you're saying "the client cancelled before receiving the instruction" that seems clear to me and text to make that explicit could help

**Comment by LPardue** [comment] 2020-10-19 22:11
@gloinul does the PR address this issue?

**Comment by gloinul** [comment] 2020-10-20 07:19
The PR provides the context for the cancellation. However, if I understand the spec correctly, you can't reneg on the encoder stream duplicate command. That is going to happen. And even if the count increase doesn't happen in B.4, why haven't it happen in B.5? I think the connection to B.5 state here is of relevance. As the examples are a seuqence, I would expect that the B.4 ends with a Insert Increment Count to acknowledge the duplication when that arrives.

**Comment by larseggert** [comment] 2020-10-20 12:21
@afrind and @MikeBishop need to weigh in on this.

**Comment by MikeBishop** [comment] 2020-10-20 14:30
It's not reneged, just not yet acknowledged.  B.5 doesn't send any encoded field sections, so there's not a requirement to acknowledge.  However, it's probably a good idea to mention in B.5 that the delayed instruction has arrived, since otherwise the decoder won't have seen the newly-added field yet.

**Comment by afrind** [comment] 2020-10-20 15:53
Example B.5 doesn't make any assertions about what the decoder has seen or not seen -- all examples show the encoder's table only.  But I can update the PR to include that note.

**Comment by larseggert** [comment] 2020-10-20 16:33
@gloinul are we ok on this one now? We'd like to merge the PR and close this.

**Comment by larseggert** [comment] 2020-10-20 16:47
@afrind & @MikeBishop: if there is no reply from @gloinul in the next hour or so (it's evening in Europe) let's please merge the PR and assume the issue is resolved.

**Comment by afrind** [comment] 2020-10-20 18:05
I'll merge as is without any changes to B5.  The text doesn't mention the decoder at all so I think it's clear enough as is.

**Closed** 2020-10-20 18:06 UTC
Labels: -qpack, editorial, ietf-lc
