### ISSUE TITLE
Clarify what to do when ALPN negotiation fails

### ISSUE THREAD

**Issue by ghedo** [quicwg/base-drafts#2495] opened 2019-03-04 15:23 UTC
PR #2314 added a requirement for end-points to terminate a connection if ALPN negotiation fails, but doesn't specify an error code for this situation.

RFC7301 defines the `no_application_protocol` alert that must be used by TLS servers, so QUIC servers should probably use that as well. As for clients, RFC7301 doesn't specify a behaviour, but it also doesn't forbid use of `no_application_protocol` in clients, and it seems better if QUIC clients use the same error code as the servers.

Proposed wording change is in #2483.

**Comment by kazuho** [comment] 2019-03-07 01:10
My :+1: goes to making the change, though I would like to confirm that it wouldn't be illegal for a client to close the connection with `no_application_protocol` error _after it sends ClientFinished_.

I ask this because depending on the design of the TLS stack, the QUIC stack might not be able to see the result of ALPN before the TLS stack generates a ClientFinished (note that EE.ALPN and ServerFinished might arrive in one packet).

It's my understanding that the intent of the issue is to not allow the client to send any application data on ALPN failure. Assuming that's true, sending the alert after ClientFinished should be fine.

**Comment by martinthomson** [comment] 2019-03-07 01:41
Yes, I think that would be fine.  I don't think that we would be able to guarantee that the alert goes out before sending ClientFinished either.  It's certainly possible, but I can see how it might be tricky.

**Comment by martinthomson** [comment] 2019-03-27 08:19
This was fixed with #2483.

**Closed by martinthomson** 2019-03-27 08:19 UTC
Labels: -tls, design, has-consensus
