### ISSUE TITLE
Transport: Ack Delay time format not specified

### ISSUE THREAD

**Issue by gloinul** [quicwg/base-drafts#612] opened 2017-06-08 08:38 UTC
In draft-ietf-quic-transport-03, Section 8.2:

   ACK Delay:  The time from when the largest acknowledged packet, as
      indicated in the Largest Acknowledged field, was received by this
      peer to when this ACK was sent.

This do not define the format of the ACK delay time.

**Comment by mikkelfj** [comment] 2017-06-08 09:04
Section 8.2.2.1 Mentions that the ACK frame uses a specific 16-bit format.

The actual format is being discussed here: https://github.com/quicwg/base-drafts/issues/109

**Comment by martinthomson** [comment] 2017-06-08 13:17
Yes, this is a duplicate of #109, which we have consensus on regarding a decision, but no text yet.

**Closed by martinthomson** 2017-06-08 13:17 UTC
