### ISSUE TITLE
kInitialRtt of 100 msec is too aggressive

### ISSUE THREAD

**Issue by pravb** [quicwg/base-drafts#2184] opened 2018-12-14 06:42 UTC
This value will cause unnecessary timeouts for CI and 0-RTT data on many Internet paths. And pretty much always on satellite links. If we want to pick a magic number then let's pick 200 msec or 300 msec (the historical minrto values for Linux and Windows respectively).

Should we add text that implementations MAY use 2 * cached path RTT if platform support is available? Even QUIC itself could maintain such a cache per path. IMO this is the right way to make Initial RTO more aggressive.

**Comment by martinthomson** [comment] 2018-12-14 06:53
I don't understand why this is a problem.  What harm, aside from retransmissing the Initial packet, does this do?

**Comment by mikkelfj** [comment] 2018-12-14 11:33
Summary from other issue: Denmark to US East Cost is just above 100ms min and avg. roundtrip. China is > 200 min and > 300 on average, and New Zealand worse than that. Denmark to Netherlands is 4ms.

So having a timeout of 100ms basically guarantees aggressive retransmission for anything but regional traffic. Maybe that is acceptable, but you can feed a lot of data on a fat pipe in 100ms, especially if you use 0-RTT and if you can tolerate replay attacks. And for space it might be worse because the link cost could be longer and bandwidth much more expensive.

**Comment by marten-seemann** [comment] 2018-12-14 14:54
We discussed this in https://github.com/quicwg/base-drafts/issues/752 and decided to err on the side of lower latency. 
@RyanAtGoogle shared some numbers there that might be more interesting than a single RTT measurement from Denmark.

**Comment by mikkelfj** [comment] 2018-12-14 14:59
Denmark happens to be my location, but it isn't entirely irrelevant with multiple data centers from Apple, Google and Facebook being constructed, and multiple new sea cables from said companies landing here. That said, no single location can be representative.

https://www.youtube.com/watch?v=iMAThVcqzuk

**Comment by ianswett** [comment] 2018-12-14 16:51
The text says "Resumed connections over the same network SHOULD use the previous connection's final smoothed RTT value as the resumed connection's initial RTT."

Did you want to broaden this to include non-resumed connections where you estimate the path RTT some other way?

**Comment by mikkelfj** [comment] 2018-12-14 17:12
> The text says "Resumed connections over the same network SHOULD use the previous connection's final smoothed RTT value as the resumed connection's initial RTT."

That at least resolves the 0-RTT concern.

**Comment by mikkelfj** [comment] 2018-12-14 18:02
With 0-RTT in check, I think the early RTO shouldn't be viewed as a failure recovery mechanism but more like a sample mechanism for discovering uncharted territory. In that light, it could go down to 10ms as long as it is only until first contact. However, because the Initial is not small (1200+ bytes), a too small original RTO would be wasteful.

So the question becomes: what is acceptable latency, what is the likely error rate, and how much bandwidth is wasted by aggressive probing.

If, for example, some common scenarios has a 66% packet loss and RTO is 100ms, you have to wait about 200ms extra to connect, even if the RTT is small, like 4ms (say noisy WLAN).

On the other hand, if the latency is high, like 500ms and the loss is small, you would be sending 5x the necessary data to connect, so 5x1200 bytes, but if you loose a packet, connectivity starts a 600ms instead of 500ms.

You could also imagine a very conservative initial RTO like 1000ms but at the same time send out small probe packets every 10ms until a valid RTT estimate is achieved, but that has its own problems in complexity and trust.

**Comment by ianswett** [comment] 2018-12-15 01:53
I've been wanting to experiment with an initial RTT based on other non-resumed connections for a while, but haven't gotten around to it in gQUIC.  It certainly seems like it'll be better than a fixed value, so I'm happy to encourage that in the spec.

**Comment by huitema** [comment] 2018-12-17 03:45
Half-way around the world is 20Km. The speed of light through optical fiber is about 100ms. Thus, halfway around the world is 100ms, and the corresponding round trip 200ms. Using 200ms by default makes sense.

**Comment by martinthomson** [comment] 2018-12-17 04:56
So we optimize for the worst case?

**Comment by kazuho** [comment] 2018-12-17 04:57
I think kInitialRTT of 100ms is conservative enough (at least for Initial packets), because a client would be retransmitting at most one packet, even when the server is at the opposite side of the world.

QUIC has 0-RTT packets that allows an endpoint to transmit several number of packets before seeing a response from the server (see also #2135), because the server "probably" knows the key to decrypt the packets. Considering the fact that we allow that, I think that retransmitting an Initial packet when it has "probably" been lost is also fine.

**Comment by martinthomson** [comment] 2018-12-17 06:46
Do we have a maximum?  I didn't think that was the subject of the discussion.  Timeouts always need to look at the tail.  Though having more packets in the pipe might allow that tail to be brought in a little more than otherwise.

As for remembering RTTs being the solution here, strengthening our reliance on mechanisms that reinforce incumbancy is the best outcome.  I certainly expect people to do that, but if that means that a site is only "fast" on return visits, that's going to disadvantage new players more.

**Comment by marten-seemann** [comment] 2018-12-17 06:46
The initial crypto retransmission timeout is reiche the initial RTT, so the first retransmission would happen after 200ms, not after 100ms. Every further retransmission will be exponentially backed off.

**Comment by huitema** [comment] 2018-12-17 06:55
@martinthomson I don't know what the practical maximum is, I don't have access to telemetry data for that. I would pick 1 second by default, or maybe 1.2 sec for 2 geo-sat hops. I don't particularly worry about having too many packets in flight, I just want to ensure that in the worst case the node has a chance to receive the response to at least the first retransmission before giving up. So I guess if the total wait time is about 1.5 sec we can be fine. Based on what @marten-seemann said, the 100 initial RTT results in a schedule of retransmissions at 200, 600, 1400 and 3000 ms, giving up 6.2 sec after the initial attempt. This seems like plenty. A bit slow, actually.

**Comment by marten-seemann** [comment] 2018-12-17 07:11
@huitema: Are you suggesting that 100ms is not aggressive enough then, especially considering Ryan's statistics in https://github.com/quicwg/base-drafts/issues/752#issuecomment-325998995?
Where does your suggestion to retransmit exactly 4 times come from?

**Comment by mikkelfj** [comment] 2018-12-17 09:37
I'd suggest increasing slightly above 100ms because US - Europe will hover between 101 - 150 ms, unless we want to almost always retransmit the Initial packet defensively on non regional links, which kind of makes sense.

**Comment by mikkelfj** [comment] 2018-12-17 10:06
I don't think Ryans estimates are particularly convincing except to ensure that QUIC also works well for that case. Any non-Google user couldn't care less about how many data centers Google use to distribute queries when deploying a QUIC application. You need to ensure QUIC works optimally well in the sub 40ms range, but the outliers needs to handled, as @huitema points out.

One option is to retransmit Initial packets 4 times in fixed intervals of 80 ms, or larger if bandwidth is expensive until at least one packet has been received by peer. The 4x ensures that one packet gets through event at loss rates up to 75% and in the typical cases at most one or two packets are sent. If there is no response after the 4th packet, the burst is repeated at increasingly larger intervals.

**Comment by ianswett** [comment] 2018-12-17 16:21
Chrome currently uses a 4 second timeout on the client if it hasn't received anything back.  That's fairly long , but 1 second is certainly to short based on what I know.  That being said, RTTs >1s are only really common on 2g, so one could use a much shorter timeout if you knew more about the network.

@mikkelfj As Marten pointed out, the current retransmission schedule is 200, 600, 1400 and 3000 ms, etc, so US/Europe connections only incur a spurious retransmit if the RTT is >200ms or there's loss.

So like Jana, I think 100ms is reasonable, but I think we should add some more text about predicting RTT based on past network measurements, even if they're not on resumed connections.

**Comment by pravb** [comment] 2019-03-25 22:24
Please see  https://www.rfc-editor.org/rfc/rfc6298.txt Appendix A for a discussion of why the 1 second minimum was suggested for TCP. Based on data quoted there, 2.5% connections will experience spurious retransmissions if initialRTO < 1 second. Since QUIC will always get an RTT sample when handshake completes, we don't need any provision to reset the InitialRTT higher even if there were timeouts.


Orthogonal to this particular issue but a total timeout of 4 seconds (or anything less than 9 seconds) is going to be a problem for VM live migrations. It's assumed that the blackout period for live migration can last as long as 9 seconds because historically TCP would always retransmit at least once after 9 seconds. I guess its not a problem for browsers but if QUIC is used in other HTTP and non-HTTP libraries then connections will break during LM.

**Comment by ianswett** [comment] 2019-03-25 22:51
Thanks for the additional information.  The data is from 2009(https://www.ietf.org/proceedings/75/slides/tcpm-1.pdf), but still seems largely plausible in terms of RTTs, though I'm sure some details have changed.

One thought is that the client may have a better idea of what it's RTT is than the server does when there is no resumption information available.  As such, we could pick a fairly conservative value(ie: 1s) on the server and if the client retransmits(and the server receives) the ClientHello more frequently,  the server should retransmit its response as well.  In practice, the current anti-amplification limit of 3x amount to exactly that in a lot of circumstances, so making it core to the handshake mechanism may be wise.  On the other hand, this is a special case unless we tweak the anti-amplification limit to be min(3 packets, initial server flight).

The 4 second timeout I mentioned is for the handshake.  I would expect live migrations to not occur during the handshake, or at least not expect the handshake to complete in that case, but maybe that's not true?  We experimented with bumping the timeout to 10 seconds a while back in gQUIC, but there were some performance regressions and we didn't dig in deeply enough to understand why.

**Comment by ianswett** [comment] 2019-03-26 11:03
The discussion in Prague concluded that we should recommend 1 second to align with RFC6298 and clarify when previous RTT estimates should be expired(ie: upon network change) and when the persisted RTT associated with 0-RTT credentials should no longer be used(ie: upon network change).

**Comment by loganaden** [comment] 2019-03-26 11:08
There are cases where the RTT is above 200ms. E.g From Mauritius to the US:

64 bytes from 208.95.3.4 (208.95.3.4): icmp_seq=1 ttl=48 time=370 ms
64 bytes from 208.95.3.4 (208.95.3.4): icmp_seq=2 ttl=48 time=387 ms
64 bytes from 208.95.3.4 (208.95.3.4): icmp_seq=3 ttl=48 time=411 ms
64 bytes from 208.95.3.4 (208.95.3.4): icmp_seq=4 ttl=48 time=492 ms
64 bytes from 208.95.3.4 (208.95.3.4): icmp_seq=5 ttl=48 time=506 ms
64 bytes from 208.95.3.4 (208.95.3.4): icmp_seq=6 ttl=48 time=370 ms
64 bytes from 208.95.3.4 (208.95.3.4): icmp_seq=7 ttl=48 time=410 ms

**Comment by ianswett** [comment] 2019-04-02 20:46
Apparently the forward and back buttons on Github don't work quite how I hoped.  In the process, I inadvertently merged this directly instead of sending it for review.

I believe the text was correct, but I'll ensure Jana verifies that today.

**Closed** 2019-04-02 22:08 UTC
Labels: -recovery, design
