### ISSUE TITLE
Define a safe algorithm for changing CID in response to a change in CID

### ISSUE THREAD

**Issue by martinthomson** [quicwg/base-drafts#1795] opened 2018-09-25 00:50 UTC
Ideally, we want an endpoint to change connection ID if its peer changes connection ID.  However, this leads to infinite changing of connection IDs if you implement the naive version of this.  We need an algorithm that is simple enough to implement, but immune to the looping problem.

This isn't critical (we can live without it), but it would be a nice to have.

Currently Section 6.11.5 is where this would live.

**Comment by mikkelfj** [comment] 2018-09-25 06:01
I'm slightly worried that some ill-advised an endpoint might spam the other endpoint with endless IDs that are being naively stored by the peer instead of retired causing a targeted or involuntary DoS attack. Even if the peer retires the IDs timely, it might not have credits to get rid of them. Of course, defense is to shut down bad behavior, but perhaps it should be considered in an advisory algorithm.

**Comment by martinthomson** [comment] 2018-09-25 17:11
@kazuho, you need a small tweak there to deal with the possibility that a peer changes >1 times before you send anything yourself.  But that seems workable.

@mikkelfj the nice thing there is that bad behaviour leads to connections closing, which seems like a good outcome.  When the only thing at stake is the continued existence of the connection, there is no need for further defenses.

**Comment by mikkelfj** [comment] 2018-09-25 18:59
@martinthomson I agree, my concern is only that this might not be obvious to implementers - in that they could kill an entire server instead of just a connection if not careful. It's a balance on how much advice to give.

**Comment by mnot** [comment] 2019-02-08 05:40
From Tokyo: duplicate of #2145

**Closed** 2019-02-13 00:23 UTC
Labels: -transport, design
