### ISSUE TITLE
QUIC Version Ossification

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#2496] opened 2019-03-04 22:09 UTC
There is a long conversation happening in the mailing list about QUIC version number ossification:
https://mailarchive.ietf.org/arch/browse/quic/?gbt=1&index=ytjKHacss9s3i3nualU2tbU9Jco
I'm adding it here to bring in others and consider it on the agenda for a WG meeting.

I won't try to summarize everyone's position from the thread. Given the status quo, it would be easy for someone to write a dumb middlebox that drops QUIC version > 1, or indeed version > 2. This appears to have happened with TLS v1.2. Given all of our effort to counter ossification, it would be tragic if we fell down on this rather simple hurdle.

There is disagreement as whether obfuscation is valuable or not. Though I have no answers, I personally would like to explore a few questions:
1) Are there any changes to VN we can make to reduce the chance of ossification happening?
2) If ossification happens anyway, do we have strategy to do something to overcome it?
3) If we are going to end up with some more obscure mechanism, does it make sense to lock in on bytes 2-5 of every long header to be 0x00000001 in perpetuity?

**Comment by mikkelfj** [comment] 2019-03-05 06:29
I originaly thought this is pointless. The registry key story both confirms that it is pointless but also, along with TLS version history, that it is a real concern.

So weak obfuscation will not work. Random values that are public will not work. Genersted values that are easy to compute will not work.

I was thinking challenge response, which is the same as init packet encryption. But that is version specific.

There need to be a time or implementation complexity component like key derivation.

But that is costly to the peers, but perhaps not too costly compared to handshake.

**Comment by kazuho** [comment] 2019-03-05 07:01
> Are there any changes to VN we can make to reduce the chance of ossification happening?

We only have obfuscation to protect the payload format of Initial packets from ossification. Therefore, IMO the question is if we can have something similar for the version number field, without making the protocol complex.

As some have pointed out, using multiple version numbers on wire to designate "version 1" is one way to go. That would be sufficient as a protection against middlebox vendors who try to use the version number field in some ways in negligence. I also think that that might be the only thing that we can do without making the "version number obfuscation scheme" an invariant.

We could do various things if we think that it is a good idea to make the obfuscation scheme an invariant. For example, we could set the version number field to a XOR value of the version number and four octets that follow the DCIL/SCIL fields (i.e. `version_number_field = version_number XOR packet[6..9]`). Such scheme would IMO require the middlebox vendors to actually consult the specification when they try to detect the QUIC protocol version. In other words, it would be as reliable as the AES-based ossification scheme we use for Initial packet payload.

**Comment by mnot** [comment] 2019-03-13 00:47
There's clearly appetite to consider this in the WG, so marking as `design`.

**Comment by philsbln** [comment] 2019-03-23 11:07
I like to re-state my earlier proposal to solve this issue by Introducing a new "Version Alias" Frame:
 - the server includes a list which other version numbers it also accepts for the currently used QUIC version
 - it also includes a timeout telling the client how long it may use these aliases.

This design allows to grease the whole version number range, e.g. by generating the aliases based on time windows and a local salt, without risking version clashes, as the alias numbers timeout. The only limitation of this scheme is that the server must make sure that the alias versions do not clash with version numbers the server is going to support within the timeout.

**Comment by mnot** [comment] 2019-03-27 08:47
Discussed in Prague; hum supported closing (with impact on applicability statement), but was not unanimous. Will try to establish consensus on-list; people who want to continue should focus on establishing a threat model.

**Comment by britram** [comment] 2019-03-27 08:48
See also quicwg/ops-drafts#62

**Comment by philsbln** [comment] 2019-04-02 09:25
With #2573, we have now a concrete description of the version alias mechanism.

Short summary:
 - It greases the version number and nonce to encrypt the client initial against ossifying on the values for v1.
 - The mechanism is optional - can be ignored / amended / removed later without changes for the rest of the protocol.
 - Without downgrade protection, it does not protect against middle boxes that actively try to force the handshake to v1.
 - With optional downgrade protection, it can be used as an early indicator for ossification.
 - With optional mandatory protection, some people fear that more middle-boxes may drop QUIC completely.

**Comment by mnot** [comment] 2019-05-22 11:39
Question in London: Do you believe that we need to ship a mechanism to mitigate version ossification prior to v1? result -- strongly in favour of addressing.

**Comment by ekr** [comment] 2019-05-22 11:42
I'm not a huge fan of this particular design, as it involves some odd state stuff.

Here's another possibility, borrowed from a design by david benjamin:

1. Each version has a random seed.
2. The version number field is computed as H(seed, <parts of the packet>)

The receiver then iterates through all the potential version numbers and checks the version number.

**Comment by martinthomson** [comment] 2019-05-22 11:44
The field is short, so collisions will happen.  The client won't necessarily know about all the versions that the server supports, so it can't know that a collision has occurred.

**Comment by ekr** [comment] 2019-05-22 11:46
Well, collisions will be quite rare unless there are a *lot* of versions. And even once there is a collision, you can test-decrypt.

Actually, it's worth noting that you could just remove the QUIC version entirely.

**Comment by martinthomson** [comment] 2019-05-22 11:48
If we go for trial decryption (which isn't that crazy), then we can drop the version number field.

**Comment by ekr** [comment] 2019-05-22 11:50
The trial-decryption version is also compatible with the ESNIKeys approach.

**Comment by mikkelfj** [comment] 2019-05-22 12:12
I like the trial decryption approach. The only problem is that random garbage sent to the server will now require not one 1200 byte trial decryption, but N such, where N is the number of supported versions. However, any trivial way to speed this up makes it equally cheap for middle boxes to filter.

There is a risk that future QUIC versions will reuse salts for initial keys to reduce the trial decryption load and encode the version information by other means.

**Comment by kazuho** [comment] 2019-05-22 13:03
As a software developer I'm happy with trial decryption. The cost is so trivial compared to public key crypto.

It could be an issue for hardware offload, though I think we can live without hardware assistance for Initial packet processing.

**Comment by kazuho** [comment] 2019-05-22 14:14
If we are to remove the version number field in favor of trial decryption, we need to figure out how a server would figure out a packet that failed to decrypt was a connection establishment attempt, so that  it can send a Version Negotiation packet. Otherwise, a client would no longer be possible to fallback to a different version.

One way of resolving the problem is to use the QUIC bit as a SYN bit. If the server fails to trial-decrypt the packet in any of the versions it supports, the server would send a Version Negotiation packet.

Having a SYN bit also helps the server, because trial decryption would only be required for packets that have the flag set.

**Comment by mikkelfj** [comment] 2019-05-22 14:35
The version field could also be replaced with zero padding and encrypted with a version 0 salt (QUIC invariant the rules that packet) and packet content nonce. If the field does not decode to 0, it was not a QUIC packet, at least not one using expected invariants.

**Comment by huitema** [comment] 2019-05-23 10:20
I am trying to summarize the set of version obfuscation proposals. I believe we have:

1) Natural versions. Just define a version 2, maybe 1bis, very quickly, and actually use version negotiation.

2) Server specific version aliases,as specified in #2573

3) Version based obfuscation and trial decryption, as proposed by David Benjamin and explained on this thread

4) Introduce a "QUIC Version" TLS extension, sent either in the clear or passed as an encrypted extension to the ESNI content.

There are pros and cons to each of those:

proposal | Pros | Cons 
--- | --- | ---
Natural version | Very little code required | Still risk of ossification
Server defined aliases | Robust prevention | Does not protect 1st packet; Requires caching code; May enable tracing
Version based obfuscation | Robust prevention | Requires trial decryption
TLS extension | Can be encrypted | Requires ESNI

**Comment by huitema** [comment] 2019-05-23 10:57
Thinking some more, I believe that David Benjamin's "version based" solution does not actually prevent ossification. The middle boxes will be programmed with the seeds of version 1. They will try decrypt with V1, and if the result is not "version = version 1" they will just say "this is not QUIC" or otherwise drop the packet.

**Comment by huitema** [comment] 2019-05-23 12:18
About the QuicVersion TLS extension: I think that EKR had a proposal already. Basically, encode the proposed version number as a TLS option. Optionally, encode the supported options in the client message, ordered by preference, and the selected option in the server response.

The client *could* send the option as a ClientHello extension, but that is not encrypted, so it does nothing t prevent ossification. But if the client sends the ESNI extension, then the TLS extension can be encrypted as part of the ESNI content, and so it is safe.

There is a downside to encoding the version in a TLS extension: it is only readable if the Initial message can be parsed. Parsing requires understanding the format of the Initial message, and that requires understanding the version used for encoding the message. That probably means accepting ossification of the Initial format, which is close to "conceding defeat".

**Comment by mikkelfj** [comment] 2019-05-23 12:28
TLS versioning assumes that all QUIC versions use TLS, which I'm not sure is a good idea.

**Comment by huitema** [comment] 2019-05-23 13:22
What if the middle-box just replies with a Version Negotiation message to any message for which it does not understand the version field? This will defeat the "natural version" and "server based obfuscation" options. For example, in the server based obfuscation case, the client will immediately repeat the request with Version 1. The middle box will cause a delay penalty, but a fairly minimal one.And we removed the protection against version downgrade from the transport spec.

**Comment by mikkelfj** [comment] 2019-05-23 13:27
We cannot prevent that if the middelbox drops the initial packet. That is an unsolvable problem because the middle box can be a valid endpoint up to and excluding TLS cert validation. But I think I have argued earlier that we should quarantine version and retry packets to see of the something better shows up before taking action.

**Comment by marten-seemann** [comment] 2019-05-23 13:29
@huitema 
> And we removed the protection against version downgrade from the transport spec.

That would be an easy thing to re-add to the transport.

**Comment by martinduke** [comment] 2019-07-23 17:51
Although I might quibble over details, I definitely support option 2 (Marten's proposal). It is one of two proposals that actually prevent ossification, as @huitema points out. Doing it in TLS introduces some dependencies on TLS people to agree to implement ESNI.

I propose that we restore the downgrade protection text and move forward with Option 2. I would like to note that it is not strictly necessary that the rest go out with v1 -- we just need a draft that a critical mass of servers and clients agree to support.

**Comment by mnot** [comment] 2019-07-24 15:02
Discussed in Montreal; EKR to lead a design team, reporting back at (or before) the next interim.

**Comment by larseggert** [comment] 2019-10-16 20:59
Discussed in Cupertino. @ekr to take #2573 and review it based on the lunch discussion in Cupertino. @kazuho to open an issue to add additional suggestions. To be closed by Singapore.

**Comment by kazuho** [comment] 2019-10-17 16:54
In Cupertino, we agreed that we'd grease the version number field (while the alternative being eliminate) and also change the salt of the Initial encryption key.

That still leaves some of the non-invariant, cleartext fields that might ossify: the long header packet type bits, token length, and packet length.

Should we scramble them too? For example, the parameters used for ossification could include a XOR bitmask that would be applied to these fields.

**Comment by RyanAtGoogle** [comment] 2019-10-17 16:56
By "Grease the version number field", I think we agreed that out-of-band, the server can communicate an alternative version number and alternative salt which can be used for future connections. Does that sound right to you?

**Comment by kazuho** [comment] 2019-10-17 17:47
@RyanAtGoogle I think that's correct, with the reservation that the medium for sending the information (e.g., alternative salt) being in debate.

**Comment by DavidSchinazi** [comment] 2019-10-19 20:54
I agree with @kazuho, I think the ossification parameters should include 2 bits used to XOR the long header type field.

**Comment by martinthomson** [comment] 2019-10-22 01:52
I think that I would prefer the NEW_TOKEN design suggested in #3111.  The additional bits seem like they might be worth adding as well.

**Comment by mnot** [comment] 2019-11-19 02:20
Discussed in Singapore; proposal is quicv2 / extension.

**Comment by janaiyengar** [comment] 2019-12-06 20:10
This should be marked v2, not proposal-ready.

**Comment by mnot** [comment] 2019-12-06 22:45
When the consensus call completes, it will be.

**Closed** 2019-12-09 00:26 UTC
Labels: -transport, design, has-consensus, quicv2
