### ISSUE TITLE
Why are setting identifiers not varints?

### ISSUE THREAD

**Issue by ekr** [quicwg/base-drafts#2233] opened 2018-12-20 23:13 UTC
Currently we are using values which would be fit in one byte, so it would
save a tiny bit of space, and given that you already have to parse the
varint for the value anyway, it wouldn't make things harder, and would
give flexibility for experimental extensions and the like.

**Comment by ianswett** [comment] 2018-12-21 21:52
Good question, using varints SGTM.

**Comment by LPardue** [comment] 2018-12-21 21:55
Dupe of https://github.com/quicwg/base-drafts/issues/1620 ?

**Comment by kazuho** [comment] 2018-12-21 22:18
+1 to making the change, because, this is the only place in H3 we use a fixed-size multi-byte number encoding.

**Comment by MikeBishop** [comment] 2019-01-31 04:46
In Tokyo, agreed to do this.

**Comment by mikkelfj** [comment] 2019-01-31 08:35
With minimal encoding.

**Comment by martinthomson** [comment] 2019-01-31 10:55
No, the conclusion was to not require minimal encoding for anything.  There is a performance argument for QUIC frames because they are used very frequently, but even that has been challenged.  The minimal encoding is only a miniscule amount more efficient, and it's more annoying to create.

**Comment by mikkelfj** [comment] 2019-01-31 15:45
It makes it slower to parse than JSON

**Closed** 2019-02-12 00:51 UTC
Labels: -http, design
