### ISSUE TITLE
Largest acked in ACK frame MUST NOT decrease

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/base-drafts#2205] opened 2018-12-18 22:17 UTC
This is implicitly assumed, and, as @martinthomson points out in [his comment](https://github.com/quicwg/base-drafts/pull/2189#discussion_r242012566), not doing so can cause undesired outcomes. There should be normative text in the transport draft requiring this behavior.

**Comment by gloinul** [comment] 2018-12-19 09:02
So the situation is that if one so far have ACKed: 1,2,3,6,7. Then if 4,5 shows up at the receiver and it is going to ACK those, it must at least send an ACK that contains 4,5 and 7, thus likely acking 4-7? It should not be allowed to send an ACK saying 4, 5 in the above situation as that doesn't indicate the receiver total progress, i.e. all the way to 7? 

I think requiring Largest Acknowledge to always indicate highest solves some issues and likely simplifies a lot of implementations. But it may result in larger ACK frames as one will have include the full current state between the largest Acknowledged and so far into the past PNs that you need to go. In severe re-ordering cases that could be a lot. 

Will this cause cause the ACK to be to large to include? Especially maybe in connections with a large delay bandwidth product going full steam encountering a serious hick up in the network. For example if an ACK is required to ack packet 4000 + 1E9 and you have 500 gaps that has arrived the last RTT/4 and really should be included. Resulting in an ACK frame that is at least 1000 bytes large, possibly bigger.

**Comment by ianswett** [comment] 2018-12-19 14:21
There are a few things this precludes, and we we should understand those before doing this.

1) A very limited implementation(ie: hardware) can't always send only one ACK block without giving up on reordered packets.  I don't have such an implementation, but at some point I remember discussing this idea with people who seemed interested in it.
2) One cannot do multipath with QUIC v1 and it means the multipath design will have to use a PN space per path, as described in Christian's draft: https://tools.ietf.org/html/draft-huitema-quic-mpath-req-01#section-4.11  I think that's likely the right choice for other reasons, but I'm hesitant to make that decision now.
3) An RTT sample can only be taken based on the largest acked.  Therefore, if there is a large amount of reordering(ie: 1RTT), you don't get any RTT samples for an RTT.  If we care about this, we can probably solve it a different way in the recovery draft, but that likely means using ack delay sometimes and not others.

In regards to Martin's comment, I thought we already had text that said ACKs with lower packet numbers than the largest ACK packet number should be ignored, since they're old?

**Comment by gloinul** [comment] 2018-12-19 14:48
@ianswett regarding your question. "In regards to Martin's comment, I thought we already had text that said ACKs with lower packet numbers than the largest ACK packet number should be ignored, since they're old?"

At least when it comes to ECN, the editors have been working hard to reformulate which has resulted in that there is nothing that applies this from the PN increasing for the ACKs. So to solve the ECN part, I think (re-)introducing that aspect into the text is the simpliest fix for ECN. But there clearly are other aspects here.

**Comment by janaiyengar** [comment] 2018-12-19 22:32
@ianswett: The problem doesn't go away if you ignore acks that are lower than largest_acked. The problem is that the receiver sent the acks in the wrong order because packets were received in the wrong order, but ECN counts are going up. 

That said, it is a corner case. I think that with the current spec, under these conditions, ECN gets turned off since validation fails. I think that's a reasonable outcome, and I'm fine with it. @gloinul?

**Comment by gloinul** [comment] 2018-12-20 10:52
ECN Validation as I currently understand it will not fail if the sender to receiver reordering happens as long as the ACKs from the receiver to sender are not reordered. So to my understanding what is missing is a requirement for the sender to no process verfication for out of order ACKs. It will not fail if the largest acknowledge is not increasing as the comparison is done on number of newly ACKed packets versus counts change.

**Comment by janaiyengar** [comment] 2018-12-20 22:59
I think #2215 is enough to address the original problem, so I'd like to close this issue. I think #2198 and #2215 are enough. @gloinul: sound ok?

**Comment by gloinul** [comment] 2019-01-07 14:59
Yes, the ECN related issue is resolved. 

What I don't know if it is resolved fully is the implementation requirements is that a sender MUST be capable of handling an ACK frame with Largest Acknowledged that is smaller than highest received? From my perspective there are good and valid arguments why this may be required, however I think consensus needs to be established on that.

**Comment by kazuho** [comment] 2019-01-07 19:57
@gloinul 
> What I don't know if it is resolved fully is the implementation requirements is that a sender MUST be capable of handling an ACK frame with Largest Acknowledged that is smaller than highest received? From my perspective there are good and valid arguments why this may be required, however I think consensus needs to be established on that.

I am not sure if I'm following the context, but my understanding is that a sender MUST be capable of that, because we allow an endpoint to simply retransmit the payload of a packet that is being deemed lost; see #1612.

**Comment by mikkelfj** [comment] 2019-01-07 20:45
Just a stray thought: is this requirement really strictly needed? It would complicate trasnmitters that split work into multiple processing units which might not be fully synced on the latest ACK'ed.

**Comment by janaiyengar** [comment] 2019-01-08 01:57
@gloinul, what @kazuho says. Also, a sender needs to be able to simply deal with reordering on the ack path. Did you mean something else?

**Comment by gloinul** [comment] 2019-01-08 10:40
My concern was primarily about the clearness of this behavior in the specification text. In transport I find the following which indicates this but are not explicit. 

13.1.1:    To limit receiver state or the size of ACK frames, a receiver MAY
   limit the number of ACK Ranges it sends.

19.3:

  Largest Acknowledged:  A variable-length integer representing the
      largest packet number the peer is acknowledging; this is usually
      the largest packet number that the peer has received prior to
      generating the ACK frame. 

I think there are strong hints, with the above "usually the largest" indicating that it is not always. I would have made this explicit in 19.3, but then I prefer being more explicit than not. I think it is possible interop issue point. Anywhere else this is more explicit? (I have read github master version)

@mikkelfj I think there are strong points for allowing an ACK frame to acknowledge only a part of the range between highest received and confirmed to be have been ACKed. The two main reasons I see.
- high rate flows suffering an packet loss burst so that the number of ACK ranges becomes to large to fit a single QUIC packet. 
- Low complexity receivers ACKing a single range of received packets and doing this for reordered packets.

**Comment by kazuho** [comment] 2019-01-08 10:47
@gloinul 
> I think there are strong hints, with the above "usually the largest" indicating that it is not always. I would have made this explicit in 19.3, but then I prefer being more explicit than not. I think it is possible interop issue point. Anywhere else this is more explicit?

As suggested by @martinthomson in #2312, 
[section 13.2](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.13.2) might be the correct place. I am advocating for describing the design principle the PR, but we might (or might not) be interested in expanding how ACK could look like.

**Comment by gloinul** [comment] 2019-01-08 12:10
So #2312 results in certain implications, that an ACK could arrive that addresses older state, thus resulting in acknowledging some PNs that was previously unacknowledged. As 13.2 is about retransmissions, I think there are other desing principle aspects of ACKs that probably should be covered, but then earlier in 13.1.

**Comment by ianswett** [comment] 2019-03-13 14:13
We're in the process of making our implementation accept smaller largest_acked values, so I'm wonder if we're any closer to consensus(one way or the other) on this issue?

**Comment by janaiyengar** [comment] 2019-05-22 13:47
I think this is mostly addressed and what's left is OBE. There's text in the draft now that says: "Processing counts out of order can result in verification failure. An endpoint SHOULD NOT perform this verification if the ACK frame is received in a packet with packet number lower than a previously received ACK frame. Verifying based on ACK frames that arrive out of order can result in disabling ECN unnecessarily."

This would be adequate, but there's other text (thanks to #2312) that says old ACKs can be resent. I think we simply add a note about that in the para above, which should be adequate.

**Comment by larseggert** [comment] 2019-05-22 13:50
Discussed in London: @janaiyengar to prepare a PR for those remaining bits

**Comment by mnot** [comment] 2019-06-14 00:25
@janaiyengar any progress here?

**Comment by ianswett** [comment] 2019-06-14 00:33
I think the conclusion here is close with no further action, but it's be good for @janaiyengar to confirm.

**Comment by janaiyengar** [comment] 2019-07-09 04:22
I've added #2879, which I believe addresses what's left of this issue.

**Comment by martinthomson** [comment] 2019-07-09 05:04
Note that we agreed that proposal-ready would be used when there were approvals for PRs (or at least apparent agreement, as determined by editors).

**Comment by janaiyengar** [comment] 2019-07-09 05:50
@martinthomson : Yeah, my bad.

**Comment by janaiyengar** [comment] 2019-08-13 23:00
This gets fixed by #2752, so marking this issue as well.

**Comment by martinthomson** [comment] 2019-08-26 07:23
Fixed by #2189.

**Closed by martinthomson** 2019-08-26 07:23 UTC
Labels: -transport, design, has-consensus
