### ISSUE TITLE
Version negotiation should only be sent for initial client packets

### ISSUE THREAD

**Issue by mikkelfj** [quicwg/base-drafts#603] opened 2017-06-07 10:24 UTC
Quote from draft-03 section 7.1:

> When the server receives a packet from a client with the long header format, it compares the client’s version to the versions it supports.
If the version selected by the client is not acceptable to the server, the server discards the incoming packet and responds with a Version Negotiation packet (Section 5.3). This includes a list of versions that the server will accept.
A server sends a Version Negotiation packet for every packet that it receives with an unacceptable version. This allows a server to process packets with unsupported versions without retaining state. Though either the initial client packet or the version negotiation packet that is sent in response could be lost, the client will send new packets until it successfully receives a response.

Later text protects against false version negotiation packets, but there is no reason for a server to respond with a version negotion packet for anything other than an initial packet, which is required to min PMTU sized. Rather, the server ought to drop packets with wrong versions in this case.

Mentioned as a related  topic here:
https://github.com/quicwg/base-drafts/issues/599#issuecomment-306747908

**Comment by mikkelfj** [comment] 2017-06-07 11:33
Related: I cannot readily find any text that says how to handle packet with an invalid version in its header, except where a server issues a version negotation packet.

I suggest any packet received with an invalid version should be ignored, except for client initial packet. If not, an adversary could jam a connection with invalid packet versions.

Stateless retry packets do not state which version to list - I suggest mirroring the client version - or require version negotiation to take place first.

**Comment by martinthomson** [comment] 2017-06-07 14:06
Duplicate of #570.

**Closed by martinthomson** 2017-06-07 14:06 UTC
