### ISSUE TITLE
Transport draft 16 Section 2.1: Stream Identifiers error handling confusion 

### ISSUE THREAD

**Issue by nekiz** [quicwg/base-drafts#1948] opened 2018-11-01 18:07 UTC
In transport draft 16, it says:

   If an endpoint receives a frame for a stream that it expects to
   initiate (i.e., odd-numbered for the client or even-numbered for the
   server), but which it has not yet opened, it MUST close the
   connection with error code STREAM_STATE_ERROR.

I believe this part (i.e., odd-numbered for the client or even-numbered for the
   server) should read as (i.e., even-numbered for the client or odd-numbered for the
   server).

**Comment by martinthomson** [comment] 2018-11-03 01:30
Duplicate of #1933.

**Closed by martinthomson** 2018-11-03 01:30 UTC
Labels: -transport, editorial
