### ISSUE TITLE
Disparity between initial_max_stream_id and MAX_STREAM_ID

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#951] opened 2017-11-21 15:49 UTC
First off, I don't know if this is really an issue. 

With the introduction of varint and unidirectional streams, there seems to be a disparity between the initial_max_stream_id TransportParameter

> The initial maximum stream ID parameter contains the initial maximum stream number the peer may initiate, encoded as an unsigned 32-bit integer. 

and MAX_STREAM_ID

>ID of the maximum unidirectional or bidirectional peer-initiated stream ID for the connection encoded as a variable-length integer. The limit applies to unidirectional steams if the second least signification bit of the stream ID is 1, and applies to bidirectional streams if it is 0.

Which one is "better"?

**Comment by MikeBishop** [comment] 2017-11-21 22:20
Duplicate of #909.

**Closed by MikeBishop** 2017-11-21 22:20 UTC
