### ISSUE TITLE
Header protection mask for server Initial packet example from -tls A.3 seems incorrect

### ISSUE THREAD

**Issue by PaulDance** [quicwg/base-drafts#4405] opened 2020-11-23 21:13 UTC
Hey there!

We are currently implementing the Initial packet encryption process and it successfully works with the client Initial example from the appendix A.2 of the QUIC-TLS draft.

However, when running tests with values for the server Initial example from the appendix A.3, tests regarding the parsing, header sampling, header protection and final encryption result all succeed, except for the header protection mask: the value we generate is: `56fb1381e7`, while the draft explicitly specifies it should be something completely different: `abaaf34fdc`. Note that the value we generate is indeed used later on for the header protection and final encryption result, which both reveal successful.

Therefore, three possibilities we thought of, in ascending order of probability:
 * Our implementation is completely broken.
 * The mask value provided by the current version of the specification (A.3) is correct, but all others are incorrect.
 * Only the mask value is incorrect, while the rest is correct.

We think the last option is the most probable one, as it could just mean it was forgotten to be updated in a recent draft version. If you think this is the case as well, then I would gladly open up a PR in order to close this, I just wanted to make sure beforehand. Otherwise, I would happily accept a tad of guidance towards a correct implementation.

Thanks in advance,
Paul.

**Comment by PaulDance** [comment] 2020-11-24 20:59
Investigated a bit more. Looking at the result of a `blame`, we can see that:

```blame
2ebdfd53a (Martin Thomson     2020-10-21 08:40:17 +1100 2214) sample = 823a5d24534d906ce4c76782a2167e34
6e9bfe065 (Martin Thomson     2020-06-04 14:39:25 +1000 2215) mask   = abaaf34fdc
2ebdfd53a (Martin Thomson     2020-10-21 08:40:17 +1100 2216) header = c7ff0000200008f067a5502a4262b5004075fb12
```

2ebdfd53a is indeed meant to update example vectors, while 2ebdfd53a is for other secrets, but the latter does is it completely.

```diff
 ~~~
-sample = 7002596f99ae67abf65a5852f54f58c3
-mask   = 38168a0c25
-header = c9ff00001d0008f067a5502a4262b5004074168b
+sample = 823a5d3a1207c86ee49132824f046524
+mask   = abaaf34fdc
+header = caff00001d0008f067a5502a4262b5004074aaf2
 ~~~
```

So it should confirm our hypothesis.

**Comment by LPardue** [comment] 2020-11-24 23:35
hi @PaulDance. Our editors are taking some slight respite, we'll respond soon.

**Comment by PaulDance** [comment] 2020-11-24 23:43
No problem @LPardue! I was just adding some more information I forgot to mention yesterday. Thanks for the heads up :+1:

**Comment by kjsisco** [comment] 2020-11-25 17:23
It seems to me that the header is not correct.  Thoughts?

**Comment by PaulDance** [comment] 2020-11-25 17:43
For me the header looks fine: it is coherent with the final result. What looks wrong to you?

**Comment by larseggert** [comment] 2020-12-04 14:19
I'll assign this to @martinthomson, since I think that is his code.

**Comment by martinthomson** [comment] 2020-12-07 10:31
I can confirm this, but it won't matter as -33 will have new values entirely.

The mask value should be 56fb1381e7 for the second example.

**Comment by larseggert** [comment] 2020-12-07 10:42
@martinthomson would you link this issue to the PR that will update the values for -33 so it gets closed then?

**Closed** 2020-12-13 22:17 UTC
Labels: -tls, editorial, ietf-lc
