### ISSUE TITLE
ClientFinished is HoL blocking, but has no normative text

### ISSUE THREAD

**Issue by ianswett** [quicwg/base-drafts#2572] opened 2019-03-31 18:48 UTC
Previous discussions have established the CFIN is HoL blocking, partially because even though it's not strictly necessary, if client auth is in use, it's critical to receive the client's entire Handshake flight before the server processes 1RTT packets.  I don't think the current TLS text is sufficiently clear(and normative) about that.

Section 4.1.1 has:
    "Important:  Until the handshake is reported as complete, the
      connection and key exchange are not properly authenticated at the
      server.  Even though 1-RTT keys are available to a server after
      receiving the first handshake messages from a client, the server
      cannot consider the client to be authenticated until it receives
      and validates the client's Finished message.

      The requirement for the server to wait for the client Finished
      message creates a dependency on that message being delivered.  A
      client can avoid the potential for head-of-line blocking that this
      implies by sending a copy of the CRYPTO frame that carries the
      Finished message in multiple packets.  This enables immediate
      server processing for those packets."

https://tools.ietf.org/html/draft-ietf-quic-tls-19#section-4.1.1

**Comment by DavidSchinazi** [comment] 2019-03-31 18:54
I agree, perhaps this section needs to say something along the lines of: `The server MUST not process received 1-RTT packets before it has validated the Client Finished, in particular it MUST NOT send acknowledgments for 1-RTT packets until before then.`

**Comment by martinthomson** [comment] 2019-04-01 05:54
How is this not a duplicate of #2458?

**Comment by martinthomson** [comment] 2019-04-01 06:23
Nevermind, I can fix this easily.

**Closed** 2019-04-09 22:09 UTC
Labels: -tls, editorial
