### ISSUE TITLE
Suggest endpoints may recognize acks after loss is declared

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3956] opened 2020-07-24 01:33 UTC
By design, TCP is capable of handling late-arriving acks. If a TCP endpoint receives an ack for a byte range after declaring loss of that byte range, retransmission of that byte range is cancelled.

In contrast, QUIC uses monotonically increasing packet numbers. That is definitely an improvement, but does have a downside. If loss detection is too sensitive, and if endpoints drop information regarding what had been sent in a packet at the moment that packet is declared lost, then it would not recognize the late acks.

I think that we should suggest (even if not recommend) QUIC endpoints to recognize late-arriving acks, so that our loss detection can be as aggressive and as effective as TCP, if not better.

(Please let me know if such text already exists. I am opening the issue because I could not find one)

**Comment by martinthomson** [comment] 2020-07-24 02:06
I have to agree.  We had to implement late acknowledgment by marking "lost" packets and retaining them.  I believe that this was very helpful in reducing the amount of redundant information we send.

Failing to retain packets that were marked as lost was also the cause of a bug. As the lost packet was removed from our outstanding calculation (a different value to the "in-flight" counter we use for congestion control), we believed that there were no packets outstanding and we didn't try to send anything when the next PTO fired.  As the loss detection timer is shorter than the PTO timer, we believed that there was nothing to send often (and we don't check all sources of frames, which would have told us otherwise).

**Comment by janaiyengar** [comment] 2020-07-24 02:33
Agreed.

**Comment by ianswett** [comment] 2020-07-24 18:36
Yeah, we should have text on this if we don't already.

**Comment by janaiyengar** [comment] 2020-07-24 22:59
The resolution in #3957 introduces a new recommendation for senders, so this ought to be considered a design issue if we're happy with that resolution.

**Comment by tatsuhiro-t** [comment] 2020-07-27 01:38
https://tools.ietf.org/html/draft-ietf-quic-recovery-29#appendix-A.1

we have this text:

```
   After a packet is declared lost, the endpoint can track it for an
   amount of time comparable to the maximum expected packet reordering,
   such as 1 RTT.  This allows for detection of spurious
   retransmissions.
```

**Comment by kazuho** [comment] 2020-07-27 01:51
@tatsuhiro-t Thank you for pointing that out. I missed that.

I tend to think that we should adopt #3957. As stated in my original comment, handling of late acks is the prerequisite of many of the normative requirements that exist in the recovery draft. Therefore, it is better to have a normative requirement for handling of late acks.

**Comment by tatsuhiro-t** [comment] 2020-07-27 02:08
I'm not opposing adding new normative text.  If new text is added, I think that the existing text should be aligned to it.  In the PR, it recommends 3PTO, but the recovery draft A.1 says 1RTT.

**Comment by martinthomson** [comment] 2020-07-27 04:10
FWIW, our implementation, as of a little while ago, tracks for `>` the current PTO.  If everything is working nicely, that limits our commitment.  As we are sending probes, the time lengthens so that we send a probe before discarding state.  If it takes two probes to get an ACK, we won't recognize that, but we will always catch an ACK for the last set of probes.  And the state commitment is minimal unless we're forced to probe.

**Comment by ianswett** [comment] 2020-07-27 14:45
I'll note that the PR is against transport, but this issue is tagged as recovery.

**Comment by janaiyengar** [comment] 2020-07-27 15:51
Thanks for pointing out this inconsistency, @tatsuhiro-t. I would argue that this should be a PTO, since that allows for including the  RTT variance in the waiting period. Using a PTO includes the maximum ack delay as well -- which may not be necessary -- but it's convenient to use the PTO period.

**Comment by ianswett** [comment] 2020-07-27 15:54
I wanted to clarify my comment on the PR about believing that 1 RTT is a preferable recommendation to 3*PTO.

We definitely don't want to discard this information BEFORE the packet is lost or acknowledged.  But after it's been declared lost, there's no need to wait longer than the reordering window to receive an acknowledgement, because an immediate ACK will be sent when the out of order packet arrives.  I tend to think an RTT is a plenty long reordering window in practice.

If nothing is inflight before and nothing sent after the packet is lost AND the late immediate ACK for the reordered packet is lost, then it could take longer than the reordering window to receive an ACK, but that seems like an edge case that's not very interesting.

**Comment by janaiyengar** [comment] 2020-07-27 16:51
@ianswett : I've changed it to 1 PTO. We've commonly used PTO as a time period for everything else in the transport, and so it's convenient to use PTO here too. Ultimately, this is the amount of time you're holding on to packets marked as lost, so the extra time waiting for a PTO (over an RTT) really shouldn't make any measurable difference. 

If you still think we should say RTT, I'm fine with that.

**Comment by kazuho** [comment] 2020-07-27 16:58
I'm fine with PTO, and I prefer PTO above RTT.

There could be reasons where there are some packet reordering due to multiple paths being used (e.g., ECMP, clustered endpoint). In such case, the variance of latency becomes more like a constant independent of RTT.

I think it is a good idea to recommend a value (i.e. PTO) that can cover such constant even if RTT is very small. PTO has `max_ack_delay` that would cover that constant.

**Comment by ianswett** [comment] 2020-07-27 19:20
I'm not convinced I understand the rationale completely, but I'm ok with 1 PTO.  I believe we should update the recovery draft in the same PR.

**Comment by larseggert** [comment] 2020-07-28 05:30
So, design?

**Comment by ianswett** [comment] 2020-07-28 14:44
We have text about this in recovery, but it's there was no normative text and it's in the appendix, so I think this is design.

**Closed** 2020-09-01 19:50 UTC
Labels: -transport, call-issued, has-consensus, wglc-post
