### ISSUE TITLE
Robert Wilton's Transport Discuss 2

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4667] opened 2021-01-07 02:38 UTC
Rob Wilton said:

> 2) In the case that the spin-bit is disabled, I don't understand the benefit of
> injecting a random spin bit value in each packet rather than always setting it
> to a per connection random value.  It seems that whether or not the randomness
> is injected, it is expected to be feasible to extract the RTT for those
> connections that are genuinely spinning the bit (or otherwise the spin bit is
> entirely pointless), but it just seems to make it computationally harder to
> extract the signal from the noise.  Perhaps the goal here is reduce the ability
> for pervasive monitoring to occur, but that feels a bit like security through
> obscurity.

**Comment by LPardue** [comment] 2021-01-07 16:09
This was talked about on the IESG telechat 2020-01-07. The action item is to add clarity one what an endpoint that does not support the spin bit should do. Note that this is distinct from an endpoint that supports spin bit but chooses to disable it. The discussion leaned towards an editorial change to the text in Section 17.4, for instance in paragraph 3.

IIUC no other changes are needed to resolve this discuss, but we should confirm this via email.

**Comment by MikeBishop** [comment] 2021-01-07 21:06
If that's the action item requested, this is a duplicate of #4666 and can be closed.

**Comment by martinthomson** [comment] 2021-01-08 00:59
Closing as a duplicate.

**Closed by martinthomson** 2021-01-08 00:59 UTC
Labels: -transport, iesg
