### ISSUE TITLE
ACK+PADDING in response to ACK should be illegal

### ISSUE THREAD

**Issue by martinduke** [quicwg/base-drafts#3100] opened 2019-10-16 21:10 UTC
quic-transport draft 13.2.1:

An endpoint MUST NOT send a packet containing
   only an ACK frame in response to a non-ACK-eliciting packet (one
   containing only ACK and/or PADDING frames),

@marten-seemann points out that this allows one to send an ACK+PADDING packet, which seems to violate the spirit of the rule. This loophole breaks #3093. I believe this may be Editorial if we all know what we meant.

**Comment by ianswett** [comment] 2019-10-16 21:50
Yes, it was intended that ACK should not elicit an ACK+PADDING packet.

**Comment by marten-seemann** [comment] 2019-10-16 21:53
I agree with this change, but I disagree that this is a satisfactory fix for #3093.

**Comment by marten-seemann** [comment] 2019-10-23 02:18
This issue should have been closed by #3104.

**Closed** 2019-10-23 02:19 UTC
Labels: -transport, editorial
