### ISSUE TITLE
Robert Wilton's Transport Comment 1

### ISSUE THREAD

**Issue by LPardue** [quicwg/base-drafts#4668] opened 2021-01-07 02:39 UTC
Rob Wiltons said:

> It would be helpful to clarify what the expected behaviour is for an
> implementation that chooses not to support the spin-bit.  Does it just leave
> the bit set as 0, or is it meant to follow the same behaviour as if spin-bit is
> supported but disabled?

**Comment by martinthomson** [comment] 2021-01-08 00:59
Closing as a duplicate of #4666.

**Closed by martinthomson** 2021-01-08 00:59 UTC
Labels: -transport, iesg
