### ISSUE TITLE
Why are there two ways of associating push with requests?

### ISSUE THREAD

**Issue by kazuho** [quicwg/base-drafts#3275] opened 2019-11-27 11:39 UTC
At the moment, the HTTP draft defines two ways of associating a pushed response with requests. One of the requests being associated uses PUSH_PROMISE, while other requests use DUPLICATE_PUSH when referring to the same pushed response.

This seems like an unnecessary complexity to me.

I wonder if we can use the following design instead:
* Send the *request of a push* on the "push stream," instead of sending it using PUSH_PROMISE.
* Merge PUSH_PROMISE and DUPLICATE_PUSH into one frame. The unified frame type would carry the PUSH_ID only.
* (Optionally) change PUSH_ID to stream ID.

I think that such change would simplify the client-side code, as there would no longer be two different logic for associating a push with a request. On the server-side, the change would also simplify the code, assuming that the server uses DUPLICATE_PUSH. My intuition that servers should be using that to avoid pushing the same resource twice on a single connection.

The argument against making such change would be that there would be no guarantee that the pushed URL would be available to the client before the client discovers the use of that pushed URL. However, in the current state, that guarantee exists only when the PUSH_PROMISE frame is being used, but not when DUPLICATE_PUSH is used. Considering that, I am doubtful if having something that *occasionally* works is worth the complexity.

**Comment by kazuho** [comment] 2019-11-27 11:55
Note also that the current design has the priority inversion issue.

When the server sends a PUSH_PROMISE frame on request stream A, then sends a DUPLICATE_PUSH frame on stream B referring to the same pushed resource, and if stream B has higher precedence than stream A, then delivery of the request header of the pushed resource might get significantly delayed. Such a behavior would have negative effect on a well-designed client that blocks on the DUPLICATE_PUSH frame until it receives the request header of the pushed resource.

Sending the request headers on the pushed stream resolves the issue. The server can more easily control the priority of a pushed stream, it becomes much easier to send the request headers of a pushed response before anything else.

**Comment by LPardue** [comment] 2019-11-27 11:55
> Send the request of a push on the "push stream," instead of sending it using PUSH_PROMISE.

How would you do this? With a HEADERS frame, or some new frame type? The reason I ask is because it would seem to change the message ordering that we have defined today (HEADERS, DATA, HEADERS)

**Comment by kazuho** [comment] 2019-11-27 12:04
@LPardue Good point. It can be a new frame, or I think it can also be a HEADERS frame.

In case of the latter, the first HEADERS frame would be the request, and the second HEADERS frame would be the response headers. This can be guaranteed since a push request is never accompanied by a request body.

**Comment by LPardue** [comment] 2019-11-27 13:09
Since you mention priority, the other question I have is at what priority is the pushed response delivered at? For example, with the proposal, the server gets request A (low precedence) and B (high precedence) it responds with unified PUSH_PROMISE on both A and B, which priority does the client believe the server is delivering the push stream with?

**Comment by dtikhonov** [comment] 2019-11-27 13:54
Having implemented DUPLICATE_PUSH on the server, I say that the complexity is increased compared with gQUIC or HTTP/2, but it's not too bad.

On the client side, the biggest problem I haven't yet solved is that push promise, when received, might not have a stream associated with it.  At that point, the user code cannot be given a push promise stream to process or refuse the push promise.  This can be solved in a few ways:
- delay informing the user that push promise has arrived until the push stream gets created;
- create a stream but delay assigning stream ID to it (and disable some stream functionality); or
- create a different API for HTTP/3 push promises.

I haven't made up my mind about which of these I dislike the least.

@kazuho's proposal would solve this problem on the client and so I agree with his argumentation regarding client complexity.  Nevertheless, the current design must have some rationale behind it, which I expect @MikeBishop to share with us on this thread.

We should also keep in mind that the HTTP draft entered Late Stage yesterday.

**Comment by LPardue** [comment] 2019-11-27 14:39
> On the client side, the biggest problem I haven't yet solved is that push promise, when received, might not have a stream associated with it. At that point, the user code cannot be given a push promise stream to process or refuse the push promise.

Caveat that I have only a very naive API for client-side push handling. I thought one purpose of the current design was to allow the proactive cancellation of pushes before the server committed stream resources, via CANCEL_PUSH.

@kazuho's proposal makes CANCEL_PUSH pretty worthless for the client (and it was already only applicable for a small time window). With this proposal the client needs to decide to cancel based on the limited information in the simplified PUSH_PROMISE. To further simplifies server push just restrict CANCEL_PUSH to be server-sent only and state that a client can only cancel pushes by issuing STOP_SENDING.

**Comment by dtikhonov** [comment] 2019-11-27 14:49
> ... one purpose of the current design was to allow the proactive cancellation of pushes before the server committed stream resources, via CANCEL_PUSH.

Good point, I've forgotten about this.

**Comment by RyanAtGoogle** [comment] 2019-11-27 20:26
> Send the request of a push on the "push stream," instead of sending it using PUSH_PROMISE.

Would that mean the that URL of the pushed resource would not be guaranteed to known to the client before a reference to that resource was referenced by the body of the main response?

**Comment by LPardue** [comment] 2019-11-27 20:27
By my understanding that woul be the case

**Comment by RyanAtGoogle** [comment] 2019-11-27 20:34
That seems like a show-stopper to me. Push is full of sharp edges already and this would add another one. I think we need a guarantee that if the server is pushing a URL, the client knows about it before it makes a request for that resource.

**Comment by kazuho** [comment] 2019-11-27 20:41
> I think we need a guarantee that if the server is pushing a URL, the client knows about it before it makes a request for that resource.

My point is that there is already no such guarantee. A client might receive a DUPLICATE_PUSH with an yet unknown PUSH_ID. In such case, the client cannot tell the URL being pushed.

**Comment by LPardue** [comment] 2019-11-27 20:48
Maybe we need something more like the gQUIC design that puts all pushes on a different stream ;)

**Comment by RyanAtGoogle** [comment] 2019-11-27 21:04
@kazuho Indeed! This is a problem for the DUPLICATE_PUSH case, but not a problem in the simple PUSH_PROMISE case. I don't like the idea of extending this problem. (And I really hate that this is a problem with DUPLICATE_PUSH at all :>).

I wonder if an alternative might be to change DUPLICATE_PUSH to include the URL of the resource being promised? (This won't be the full request headers, but at least it would include the URL).

**Comment by LPardue** [comment] 2019-11-27 21:18
I had a similar thought, but then you're on a slippery slope towards sending the complete pseudo-request and back to the problem we had with coordinationating different promises with the same push ID that led to DUPLICATE_PUSH

**Comment by kazuho** [comment] 2019-11-27 21:27
@RyanAtGoogle @LPardue I actually think that sending PUSH_PROMISE with the entire set of request headers *on all request streams that refer to the same push* would be a reasonable approach. The client can then check that the request headers are equivalent.

Doing so also solves HoLB caused by priority inversion (see https://github.com/quicwg/base-drafts/issues/3275#issuecomment-559056999).

I do not anticipate that the there would be many request headers within a push, so sending all the request headers would not be a big concern regarding bandwidth.

**Comment by LPardue** [comment] 2019-11-27 21:31
That takes us to revisiting https://github.com/quicwg/base-drafts/issues/1864

**Comment by RyanAtGoogle** [comment] 2019-11-27 21:34
@kazuho I'd be supportive of replacing DUPLICATE_PUSH with a duplicate PUSH_PROMISE which would, as @LPardue points out, revisit #1864. Otherwise I fear we end up with yet another sharp edge with push which seems highly sharp already.

**Comment by martinthomson** [comment] 2019-11-27 22:47
I don't see any new information here.  The design we have is the result of balancing the need to have certain information in order with responses (as @RyanAtGoogle points out) and the desire to avoid the complexity and costs of duplication.

One advantage of the current design is the ability to exercise flexibility.  There is nothing preventing someone from pushing the same thing twice in this design, thereby avoiding DUPLICATE_PUSH.

Having implemented this, both at the server and the client, I can say that it is awkward, but not terribly so.  DUPLICATE_PUSH is a little tricky to thread on the server side, primarily due to it being hard to find something that is worth duplicating.  The client has no real problem with it other than the obvious ordering issue.  In that case, the simplest course is to proceed as though no push were promised until the PUSH_PROMISE arrives.

The possibility of priority inversion exists, but as pushes are discretionary, I don't see a significant downside.  Like QPACK, it's a discretionary feature and the server can make its own decisions about the risks.

**Comment by RyanAtGoogle** [comment] 2019-11-27 23:01
I agree that there's no new information here; I just really dislike the sharp edge of the current DUPLICATE_PUSH behavior:

>  In that case, the simplest course is to proceed as though no push were promised until the PUSH_PROMISE arrives.

Indeed, that is the simplest course. But unless all user-agents do the same thing it means that servers can't rely on particular client-side behavior which is a real bummer. Push is already hard enough to get right (in both clients and servers) it seems like adding more rough edges runs the risk of resulting in push being disabled/removed from some implementations. (I believe Brad Lassey from Chrome presented at IETF 102 data which suggested doing exactly this)

**Comment by kazuho** [comment] 2019-11-28 00:13
@LPardue @martinthomson Apologies for not chiming in to the discussion in #1864.

@martinthomson 
> One advantage of the current design is the ability to exercise flexibility. There is nothing preventing someone from pushing the same thing twice in this design, thereby avoiding DUPLICATE_PUSH.

I do not think that is something that a server should do, as it would mean that the server would be pushing not only the headers but the entire response multiple times to the client.

@RyanAtGoogle 
> But unless all user-agents do the same thing it means that servers can't rely on particular client-side behavior which is a real bummer. Push is already hard enough to get right (in both clients and servers) it seems like adding more rough edges runs the risk of resulting in push being disabled/removed from some implementations. (I believe Brad Lassey from Chrome presented at IETF 102 data which suggested doing exactly this)

+1

I can see @martinthomson's view that push is feature that the server might use, and therefore that it can be complicated. But as the number of traps increases in the protocol, it becomes more likely that some stacks (or some combination of client- and server-side stacks) would have edge cases that lead to worse performance when push is used.

In HTTP/2, push is a feature that is often misused, leading to performance degradation, even though the protocol itself is designed correctly. The situation would become worse in HTTP/3, if we introduce uncertain behaviors to the protocol design (i.e., some clients might not block on DUPLICATE_PUSH).

**Comment by RyanAtGoogle** [comment] 2019-12-03 05:22
This is likely the wrong place for this observation, but I'll mention it here. Ian and I were chatting about this issue and realized a couple of things about HTTP/3 push which were quite surprising.

Recall that in HTTP/2, the motivating use case for PUSH_PROMISE was the ability to promise more resources than the open stream limit would allow to be pushed. (Consider an image search in which the server wants to push a grid of 100 thumbnails when the open stream limit is 10). 

The server would be able to push all 100 of these thumbnails in a single RTT (assuming sufficient BDP) because in HTTP/2 the sever can open a new stream as soon as the previous stream is closed.

However, in HTTP/3 this is not the case. The server will be unable to open a new push stream until it receives a new MAX_STREAMS from the client increasing the limit. But that burns an RTT. In which case, there's no point in pushing at all. So to avoid this, a client could increase the MAX_STREAMS to some sort of enormous value. But that does not behave like the HTTP/2 open stream limit. 

As such I'm not sure the original motivation for PUSH_PROMISE makes sense in HTTP/3. On the other hand, PUSH_PROMISE does something totally different in HTTP/3. It provides an ordering guarantee between the promised headers and the the reference to the resource in the main response body.

What's the conclusion of all this? I'm not sure. But it raises a few points:
* HTTP/3 server push works incredibly differently than HTTP/2
* At a minimum we should probably provide advice about how the client should manage MAX_STREAMS and MAX_PUSH_ID
* I could almost imagine replacing PUSH_PROMISE completely by a BLOCK_UNTIL_PUSH_RECEIVED frame which specifies a QUIC stream ID and prevents the app from processing the rest of the body until the specified push stream's initial headers are received.

Thoughts? Does this resonate with anyone?

**Comment by kazuho** [comment] 2019-12-03 06:15
@RyanAtGoogle I kind of agree, and kind of disagree.

> * HTTP/3 server push works incredibly differently than HTTP/2

I am not sure how different they are. As you correctly point out, the benefit you achieve by pushing is limited to one BDP in HTTP/2. As there is the potential of pushing a response that has already been cached by the client, pushing too much has been a bad idea in HTTP/2. IMO, the fact that we are additionally capped by the push stream concurrency in HTTP/3 does not change the big picture.

> * At a minimum we should probably provide advice about how the client should manage MAX_STREAMS and MAX_PUSH_ID

SGTM.

> * I could almost imagine replacing PUSH_PROMISE completely by a BLOCK_UNTIL_PUSH_RECEIVED frame which specifies a QUIC stream ID and prevents the app from processing the rest of the body until the specified push stream's initial headers are received.

I presume that's the same as what I originally proposed in this issue? Personally, I think I am fine with either ways. What I'm unhappy with status-quo is that there is two ways of doing one thing, which is causing complexity.

**Comment by RyanAtGoogle** [comment] 2019-12-03 15:21
> I am not sure how different they are. As you correctly point out, the benefit you achieve by pushing is limited to one BDP in HTTP/2. As there is the potential of pushing a response that has already been cached by the client, pushing too much has been a bad idea in HTTP/2. IMO, the fact that we are additionally capped by the push stream concurrency in HTTP/3 does not change the big picture.

In HTTP/2, pushing too much is only a problem when you push something that the client already has cached (or otherwise does not need) or if you invert the priorities and push something instead of sending something more important. But in HTTP/2 there is no performance problem with pushing an unlimited number of resources, so long as they are all "required" and "important".

This is not the case with push. Promising more resources than the concurrent stream limit is a performance regression. I think this is non-obvious.

> > * I could almost imagine replacing PUSH_PROMISE completely by a BLOCK_UNTIL_PUSH_RECEIVED frame which specifies a QUIC stream ID and prevents the app from processing the rest of the body until the specified push stream's initial headers are received.
> 
> I presume that's the same as what I originally proposed in this issue? Personally, I think I am fine with either ways. What I'm unhappy with status-quo is that there is two ways of doing one thing, which is causing complexity.

I think this could be what you proposed initially, though I have one point of clarification. I understood the DUPLICATE_PUSH semantics to be that the client would continue to process the body of the stream on which the DUPLICATE_PUSH was sent, but that any requests would be blocked until the associated PUSH_PROMISE was received. I don't like this idea because it blocks all requests, not just those which the server intended to promise. Instead, I'd propose that the frame (whatever we call it) blocks the processing of the stream on which the frame was sent, which prevents the client from discovering the link to the promised resource until the push headers have arrived. (Of course the server should send the push headers on the push stream before it sends the frame on the original stream thus typically the push headers will arrive before the frame).

Is this latter behavior what you were thinking?

**Comment by LPardue** [comment] 2019-12-03 15:39
> Recall that in HTTP/2, the motivating use case for PUSH_PROMISE was the ability to promise more resources than the open stream limit would allow to be pushed. (Consider an image search in which the server wants to push a grid of 100 thumbnails when the open stream limit is 10).

Was that a feature or a bug? By my understanding, we've been attempting to fix that accounting loophole in HTTP/3.

Some of what is being discussed here is a retread of #2559 (in particular https://github.com/quicwg/base-drafts/issues/2559#issuecomment-476961392)

> However, in HTTP/3 this is not the case. The server will be unable to open a new push stream until it receives a new MAX_STREAMS from the client increasing the limit. But that burns an RTT. In which case, there's no point in pushing at all. So to avoid this, a client could increase the MAX_STREAMS to some sort of enormous value. But that does not behave like the HTTP/2 open stream limit.

I don't follow. The HTTP/2 behaviour seems to equate to constrained concurrent requests, and uncontrained pushes. Therefore, setting a sensible value for `MAX_STREAMS bidi` and an enormous value for `MAX_STREAMS uni` seems like what you want. Although I not convinced that is a feature.

> At a minimum we should probably provide advice about how the client should manage MAX_STREAMS and MAX_PUSH_ID

If you're trying to mimic the "push 100 tumbnails without an RTT" behaviour, you'll have to keep in mind the value of initial_max_stream_data_uni too.

**Comment by RyanAtGoogle** [comment] 2019-12-03 16:07
> > Recall that in HTTP/2, the motivating use case for PUSH_PROMISE was the ability to promise more resources than the open stream limit would allow to be pushed. (Consider an image search in which the server wants to push a grid of 100 thumbnails when the open stream limit is 10).
> 
> Was that a feature or a bug? By my understanding, we've been attempting to fix that accounting loophole in HTTP/3.

It was definitely a feature! (Though the lack of *any* limit on the number of promised resources might have been a bug). In particular, the feature came into existence because, iirc, because Roberto tried to do a server push demo of exactly this use case (page of thumbnails) but it didn't work because the stream limits got in the way. After that, he proposed the push/promise distinction with the explicit intent of allowing more promises than pushes.
 
> Some of what is being discussed here is a retread of #2559 (in particular [#2559 (comment)](https://github.com/quicwg/base-drafts/issues/2559#issuecomment-476961392))

Agreed. To be clear, I rather like the explicit MAX_STREAMS signal. For bidirectional streams and web browsing, this seems to work out extremely nicely.

For server push, on the other hand, it's a non-obvious sharp edge, particular with respect to HTTP/2. (So at a minimum, I think we should provide guidance on how to push with HTTP/3 effectively)

> > However, in HTTP/3 this is not the case. The server will be unable to open a new push stream until it receives a new MAX_STREAMS from the client increasing the limit. But that burns an RTT. In which case, there's no point in pushing at all. So to avoid this, a client could increase the MAX_STREAMS to some sort of enormous value. But that does not behave like the HTTP/2 open stream limit.
> 
> I don't follow. The HTTP/2 behaviour seems to equate to constrained concurrent requests, and uncontrained pushes. Therefore, setting a sensible value for `MAX_STREAMS bidi` and an enormous value for `MAX_STREAMS uni` seems like what you want. 

Not quite. HTTP/2 provides unlimited *promises*, but limited concurrent *pushes* (via the open steams limit). HTTP/3 can limit promises via MAX_PUSH_ID, and limit concurrent pushed via MAX_STREAMS uni. So to replicate HTTP/2, and HTTP/3 client could try a huge MAX_PUSH_ID and a small MAX_STREAMS uni. That would have the same concurrent behavior as HTTP/2, but would run the risky of adding a 1-RTT delay for pushes above the MAX_STREAMS limit.

> Although I not convinced that is a feature.

That's a fair point. If so we should probably have guidance how managing MAX_PUSH_ID and MAX_STREAMS uni together to make this obvious. (Though at this point I'm coming around the to position of other folks in Chrome that push in general is rarely a performance win and typically a footgun and we should stop using it)
 
> > At a minimum we should probably provide advice about how the client should manage MAX_STREAMS and MAX_PUSH_ID
> 
> If you're trying to mimic the "push 100 tumbnails without an RTT" behaviour, you'll have to keep in mind the value of initial_max_stream_data_uni too.

Yes, flow control also comes into play for sure. (Thankfully that's not much different from HTTP/2). If a client's flow control limits are less than a BDP, the client is "gonna have a bad time" :)

**Comment by kazuho** [comment] 2019-12-04 02:35
I tend to agree with what @RyanAtGoogle says.

IIUC, one of the reasons we have push ID in addition to stream IDs is to limit the exposure of transport features to the application protocol. However, as @ianswett points out in #3273, there is already a leak in the abstraction.

Therefore, I think we can (and should) directly use stream IDs. Doing so would resolve the concern that the push might get blocked by stream concurrency.

>>> * I could almost imagine replacing PUSH_PROMISE completely by a BLOCK_UNTIL_PUSH_RECEIVED frame which specifies a QUIC stream ID and prevents the app from processing the rest of the body until the specified push stream's initial headers are received.
>>
>> I presume that's the same as what I originally proposed in this issue? Personally, I think I am fine with either ways. What I'm unhappy with status-quo is that there is two ways of doing one thing, which is causing complexity.>
> 
> I think this could be what you proposed initially, though I have one point of clarification. I understood the DUPLICATE_PUSH semantics to be that the client would continue to process the body of the stream on which the DUPLICATE_PUSH was sent, but that any requests would be blocked until the associated PUSH_PROMISE was received. I don't like this idea because it blocks all requests, not just those which the server intended to promise. Instead, I'd propose that the frame (whatever we call it) blocks the processing of the stream on which the frame was sent, which prevents the client from discovering the link to the promised resource until the push headers have arrived. (Of course the server should send the push headers on the push stream before it sends the frame on the original stream thus typically the push headers will arrive before the frame).
> 
> Is this latter behavior what you were thinking?

To me, those two approaches sounds like something that a client can choose from, though I agree that the latter is better as it introduces less blocking. If the HTTP/3 draft is not already clear about the intention, it might be a good idea to open an editorial issue, because IMO that is a problem with the DUPLICATE_PUSH frame that already exists.

**Comment by martinthomson** [comment] 2019-12-04 03:17
Unlimited pushes in HTTP/2 was a bug, not a feature.  The concurrency limit might have applied in theory, but the ability to run the entire stream lifecycle without feedback meant that there was no limit in practice other than those imposed by TCP - on either promises or responses.

The important feature, which we retained, was the ability to decouple the stream limits and the number of promises.  That's why we have push IDs.  Assuming the client is configured for that, the separate limit on push promises ensures that promises can greatly exceed the number of active streams.  I think that is the ideal situation if the client is somehow resource-limited, so it can accept N promises and then receive M (<N) responses for those promises.

In other words, I see no reason to change the current design.  If this is the result of general antipathy toward server push, that's fine, but we're not in a stage of development where we can afford to make changes at such a fundamental level without serious impact on our schedule.  Besides, I'm not seeing a proposal here that would be anything less than a regression in some way.

If someone wants to contribute text that walks through some of the trade-offs inherent in setting different limits (whether that be streams, flow control, or push IDs) for people who might want to implement or deploy HTTP, that seems fine.  As this is highly context-dependent, it might be hard to avoid certain biases.  I certainly wouldn't want to block publication if such guidance were absent.

**Comment by ianswett** [comment] 2019-12-04 13:54
I'd suggest removing DUPLICATE_PUSH and allowing duplicate PUSH_PROMISE frames on different response streams.  I'd be hesitant to make larger changes at this point and I think Push IDs are an improvement over HTTP/2.

DUPLICATE_PUSH saves a few bytes over an equivalent PUSH_PROMISE, but I believe has no value.  Think of the two cases:
1) No loss or reordering, the client has already received the PUSH_PROMISE.  DUPLICATE_PUSH should not change the client response.
2) DUPLICATE_PUSH arrives before PUSH_PROMISE.  But the client doesn't know what was pushed.  It has the choice of indefinitely delaying all requests on the page, which is almost certainly a performance degradation in most cases or ignoring it.

**Comment by LPardue** [comment] 2019-12-04 14:05
> I'd suggest removing DUPLICATE_PUSH and allowing duplicate PUSH_PROMISE frames on different response streams.
> DUPLICATE_PUSH saves a few bytes over an equivalent PUSH_PROMISE, but I believe has no value.

What we have now addresses a specific concern raised on #1864 about how to handle multiple PUSH_PROMISES with the same ID. Mike suggested some points that could be address on that ticket https://github.com/quicwg/base-drafts/issues/1864#issuecomment-430697483 if we continued to allow multiple PUSH_PROMISE:

>     * Maintains a list of active promises for which it is still willing to accept an additional reference to the promise, including the uncompressed headers for the promise (likely until the promise is fulfilled, possibly plus a timeout)
>     * Verifies that the headers match exactly when receiving an additional reference to one of these promises; MUST error if they don't.
>     * If a promise is received for an ID which has already been flushed from the list, the promise is ignored

A PR that proposes removing DUPLICATE_PUSH should address the above.

**Comment by MikeBishop** [comment] 2019-12-16 16:33
> Nevertheless, the current design must have some rationale behind it, which I expect @MikeBishop to share with us on this thread.

I think I've been adequately channeled in the meantime.  😉

As others have pointed out, this was a compromise that no one was thrilled about, but was considered better than the status quo and no ingenious solution to all issues has yet presented itself.  The solution space that I see is:

- **One request, one promise, one push.**  H2-style, every push is promised to one and only one request.
- **Multiple PUSH_PROMISE frames on different streams.**  Old H3-style; wastes some bytes repeating yourself, and now we have to talk about consistency between them:
  - **Allowed to differ**; each promise separately contains the headers of the request, and if different requests would have garnered identical responses, this is fine.  (For example, pushing "empty list" for lots of subresources the client might have wanted to retrieve as part of an API.)
  - **Not allowed to differ**; client has to check that the headers are the same.  What if they're not?  How long does the client have to keep the headers?  Need it be the same bytes, or simply the same resulting header set?
- **Headers sent once; DUPLICATE_PUSH frame.**  This is the compromise we landed on.  It's true that this means the headers might not be available at the point DUPLICATE_PUSH is received.
- **Headers sent once on push stream; DUPLICATE_PUSH becomes PUSH_PROMISE.**  Conceptually easier, but means headers are almost certainly not available at the point the promise is received.  Means promised request can't be delivered without enough stream credit to do the push itself.

The idea of including a URI in DUPLICATE_PUSH is an interesting one, and might reduce the amount of blocking clients need to do until the push request is received.  It also makes that last solution more palatable.  Presumably, if the server is pushing a request for a URI, the odds that the request will match what the client would have sent better be high.

I don't personally believe this change is warranted in late stage, but I'm willing to take an improvement the working group reaches consensus on.

**Comment by kazuho** [comment] 2019-12-17 04:53
@MikeBishop Thank you for laying down the options.

My preference goes to:

> * **Multiple PUSH_PROMISE frames on different streams.** Old H3-style; wastes some bytes repeating yourself, and now we have to talk about consistency between them:
>   * **Not allowed to differ**; client has to check that the headers are the same. What if they're not? How long does the client have to keep the headers? Need it be the same bytes, or simply the same resulting header set?

Regarding the points listed as questions, I think we should state that the header set that the server sends MUST contain the exact same bytes (after decompression), and that a client MUST either validate that they are the same, or ignore the PUSH_PROMISE.

By using MAX_PUSH_ID frame, the client controls the number of pushes that the server can initiate. It can track the unused push IDs much like the QUIC transport tracks unused stream IDs. By tracking that, the client can tell if a PUSH_PROMISE frame contains a new push or if is a duplicate. If it is a duplicate that it has already forgotten, then it can simply ignore it.

**Comment by RyanAtGoogle** [comment] 2019-12-17 05:20
+1 to everything @kazuho said. Let's do it!

**Comment by LPardue** [comment] 2019-12-17 07:10
What do you mean by "exact same bytes"? After decompression I'm converting to my own header list object that isn't the same layout as any interop standard, is that ok?

**Comment by kazuho** [comment] 2019-12-17 07:42
@LPardue I mean that the set of headers should appear in the same order, and that each of the header fields should contain the same bytes (after decompression).

Or to paraphrase, they should be the same byte-by-byte once decompressed, rather than semantically being the same. For example, the number of white spaces between the cache-control directives cannot change.

**Comment by RyanAtGoogle** [comment] 2019-12-20 16:07
Not sure if I'm doing Gituhub right, but I just cooked up a PR to remove DUPLICATE_PUSH and permit duplicate PUSH_PROMISE frames which must contain the same headers.

**Comment by ianswett** [comment] 2020-01-07 20:08
@larseggert or @mnot can you mark this as design?

**Comment by martinthomson** [comment] 2020-01-08 00:25
Out of the discussion here only one thing changed my mind: utility.  A client that receives DUPLICATE_PUSH after PUSH_PROMISE receives no new actionable information, so the main question is what happens when DUPLICATE_PUSH precedes PUSH_PROMISE.  In that case, the appearance of a new resource that *might* be pushed creates uncertainty in the client.

The client might hold requests on the basis that something is forthcoming, but they don't know which resource, or even where to block.  If there was a URL, you could answer the what question; if there was a stream ID for the original promise you could answer the where question and maybe block on that stream instead (yay, more cross-stream dependencies!).

But in the end, it seems better to not build the additional complexity.  Allow duplicate PUSH_PROMISES and require that they be sent with the same content, but not require that receivers check (allow them to assume equality).  I don't have an opinion on byte-for-byte equality post-QPACK-decode, but I wouldn't want byte-for-byte equality on the encoded contents as that imposes restrictions on implementations.  If enforcement of equality is discretionary or opportunistic, then we can afford to let the enforcer do a little more work.

The current PR seems about right on all counts.

**Comment by kazuho** [comment] 2020-01-08 01:31
I'm also fine with current PR.

"MUST error if detecting a mismatch" works for me. While it would not be that difficult to implement  "MUST detect mismatch or ignore PUSH_PROMISE" rule, it is a different question if we need to enforce that as a protocol specification.

**Comment by MikeBishop** [comment] 2020-01-08 16:47
@martinthomson advocated that if they're required to be the same, then a server that's violating that deserves any unexpected behavior they uncover on clients.  That makes me slightly nervous, because that way lies servers depending on particular client behavior in bizarre situations.  I still lean toward "SHOULD either check or discard; MUST error if detected" to guard against that, but I agree it's not critical for protocol compatibility that the client validate.

**Comment by RyanAtGoogle** [comment] 2020-01-09 23:22
@MikeBishop does the current PR text satisfy you or would you like it to explicitly say something about discarding? Here's the current PR text:

If a client receives a Push ID that has already been promised
and detects a mismatch, it MUST respond with a connection error of type
H3_GENERAL_PROTOCOL_ERROR. If the decompressed header sets match exactly, the
client MUST ignore the duplicate PUSH_PROMISE frame.

**Closed** 2020-02-11 20:27 UTC
Labels: -http, design, has-consensus
