### ISSUE TITLE
Confusion in the text between packets, frames and datagrams

### ISSUE THREAD

**Issue by larseggert** [quicwg/base-drafts#4290] opened 2020-10-28 14:11 UTC
>14.  Datagram Size
>
>  A UDP datagram can include one or more QUIC packets.

There is some confusion in the text between packets, frames and datagrams.
That could be helped by earlier clarification.

**Comment by MikeBishop** [comment] 2020-10-28 19:59
This is a duplicate of #4266.

**Closed** 2020-11-03 23:14 UTC
Labels: -transport, ietf-lc
