### ISSUE TITLE
endpoints don't know how many connection IDs the peer is willing to store

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/base-drafts#1994] opened 2018-11-12 10:46 UTC
As discussed on the list and in #1992, the fact that endpoints don't know how many connection IDs the peer is willing to store, leads to some undesirable consequences, which I described in https://github.com/quicwg/base-drafts/pull/1992#pullrequestreview-173829561:

Issuing too many connection IDs doesn't hurt in the case where the server uses a deterministic routing scheme to associate connection IDs to connections (except for the obviously wasted bandwidth). However, there's a different approach (which I chose in my implementation). I'm keeping a mapping connection ID => connection around for every single connection ID I issue. This allows me to use very short (4 bytes) connection IDs. If an implementation like this issues too many connection IDs, and the peer starts dropping them, it will have to keep state for every dropped connection ID until the end of the connection.

I'm preparing a PR to introduce a transport parameter, which will allow an endpoint to declare how many connection IDs it is willing to receive. It's late in Thailand already, so please give me until tomorrow this time to finalize the text for that.

**Comment by mikkelfj** [comment] 2018-11-12 10:58
Supporting this.

Please include text on how to handle too many CID's received (probably protocol violation).

I wonder if some kind of delay is meaningful e.g. waiting until 1/4 is retired before issuing new CID's rather than dripping. Or, retire could retire multiple in a batch to achieve the same effect. Or maybe that is altogether unimportant?

**Comment by dtikhonov** [comment] 2018-11-12 13:55
Once the issuer knows how many the other side stores, it can batch connection IDs as it will be able to assess whether the peer has available CIDs.

**Comment by MikeBishop** [comment] 2018-11-13 19:26
I'm not convinced this is dire, since you're only going to issue as many CIDs as you're comfortable maintaining.  However, it is a waste of bandwidth and mapping resources to send more than the peer wants to work with, so I suspect this is marginally better.

**Comment by janaiyengar** [comment] 2018-11-14 11:40
What @MikeBishop said.

**Comment by ekr** [comment] 2018-11-23 19:09
I'm not sure we need this, but if we are going to bother to have it, then it should be a target. I.e., the other side should be required to keep you full, not just not to send you any more than this.

I'm also concerned by the semantics of having exceeding the max be an error, because it introduces pressure to increase max. The issue is that what you want to have is spare CIDs, and right now the only real way to elicit new CIDs is to RETIRE, but while that's in flight, if the other side is at max it can't send more, so this makes things more brittle.

**Comment by ianswett** [comment] 2018-11-24 01:43
One idea: In an effort to enforce the principles, but not be overly strict or complex, maybe allow the connection to be closed with an error if a NEW_CONNECTION_ID frame is received with an ID that's more than the max_connection_ids from the largest retired connection id(or 0 if no ids have been retired)?

**Comment by martinthomson** [comment] 2018-11-26 03:41
As others have said, this makes things more deterministic, but more complex.  I'm going to suggest that this is fertile ground for extensions. We can't know what the right answer is today, and it's going to take some deployment experience to get it right.  More machinery will likely only interfere with our ability to deploy fixes if they are needed.  And if no fixes are needed...success.

**Comment by RyanAtGoogle** [comment] 2018-11-30 23:56
I agree with ianswett here. If there's a limit that an endpoint is allowed
to set on the number of connection IDs that it stores, it should
communicate that limit to the peer. Anything else seems like it sets us up
for subtle interop bugs down the road. (And if I have a limit which the
peer knows and exceeds, then closing the connection seems great.)

**Comment by martinthomson** [comment] 2019-01-30 05:47
Tokyo conclusion: @marten-seeman will amend the PR to remove the error condition - the transport parameter will be a hint.

**Comment by mnot** [comment] 2019-04-23 07:16
@janaiyengar the relevant PR is #1998, correct?

**Comment by janaiyengar** [comment] 2019-04-23 08:18
@mnot : Yes.

**Closed** 2019-05-02 09:57 UTC
Labels: -transport, design, has-consensus
